# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import Annotated, Callable, ClassVar, Literal, overload

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class ClusterEphemeralReportSpecOwner(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpecOwner"]:
            return ClusterEphemeralReportSpecOwner

        def build(self) -> "ClusterEphemeralReportSpecOwner":
            return ClusterEphemeralReportSpecOwner(**self._attrs)

        def api_version(self, value: str, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def block_owner_deletion(self, value: bool | None, /) -> Self:
            'If true, AND if the owner has the "foregroundDeletion" finalizer, then\nthe owner cannot be deleted from the key-value store until this\nreference is removed.\nSee https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion\nfor how the garbage collector interacts with this field and enforces the foreground deletion.\nDefaults to false.\nTo set this field, a user needs "delete" permission of the owner,\notherwise 422 (Unprocessable Entity) will be returned.'
            return self._set("block_owner_deletion", value)

        def controller(self, value: bool | None, /) -> Self:
            "If true, this reference points to the managing controller."
            return self._set("controller", value)

        def kind(self, value: str, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str, /) -> Self:
            "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names"
            return self._set("name", value)

        def uid(self, value: str, /) -> Self:
            "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids"
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["ClusterEphemeralReportSpecOwner.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpecOwner.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecOwner."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterEphemeralReportSpecOwner", Builder]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecOwner, ClusterEphemeralReportSpecOwner.Builder
        ]()

    api_version: Annotated[str, Field(alias="apiVersion")]
    "API version of the referent."
    block_owner_deletion: Annotated[bool | None, Field(alias="blockOwnerDeletion")] = None
    'If true, AND if the owner has the "foregroundDeletion" finalizer, then\nthe owner cannot be deleted from the key-value store until this\nreference is removed.\nSee https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion\nfor how the garbage collector interacts with this field and enforces the foreground deletion.\nDefaults to false.\nTo set this field, a user needs "delete" permission of the owner,\notherwise 422 (Unprocessable Entity) will be returned.'
    controller: bool | None = None
    "If true, this reference points to the managing controller."
    kind: str
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str
    "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names"
    uid: str
    "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids"


class ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem"]:
            return ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem

        def build(
            self,
        ) -> "ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem":
            return ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem(
                **self._attrs
            )

        def key(self, value: str, /) -> Self:
            "key is the label key that the selector applies to."
            return self._set("key", value)

        def operator(self, value: str, /) -> Self:
            "operator represents a key\u0027s relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist."
            return self._set("operator", value)

        def values(self, value: list[str] | None, /) -> Self:
            "values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch."
            return self._set("values", value)

    class BuilderContext(
        BuilderContextBase[
            "ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = (
                ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder()
            )
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem",
        Builder,
    ]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem,
            ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder,
        ]()

    key: str
    "key is the label key that the selector applies to."
    operator: str
    "operator represents a key\u0027s relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist."
    values: list[str] | None = None
    "values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch."


class ClusterEphemeralReportSpecResultsItemResourcesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpecResultsItemResourcesItem"]:
            return ClusterEphemeralReportSpecResultsItemResourcesItem

        def build(self) -> "ClusterEphemeralReportSpecResultsItemResourcesItem":
            return ClusterEphemeralReportSpecResultsItemResourcesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def field_path(self, value: str | None, /) -> Self:
            'If referring to a piece of an object instead of an entire object, this string\nshould contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].\nFor example, if the object reference is to a container within a pod, this would take on a value like:\n"spec.containers{name}" (where "name" refers to the name of the container that triggered\nthe event) or if no container name is specified "spec.containers[2]" (container with\nindex 2 in this pod). This syntax is chosen only to have some well-defined way of\nreferencing a part of an object.'
            return self._set("field_path", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
            return self._set("namespace", value)

        def resource_version(self, value: str | None, /) -> Self:
            "Specific resourceVersion to which this reference is made, if any.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"
            return self._set("resource_version", value)

        def uid(self, value: str | None, /) -> Self:
            "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"
            return self._set("uid", value)

    class BuilderContext(
        BuilderContextBase["ClusterEphemeralReportSpecResultsItemResourcesItem.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpecResultsItemResourcesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecResultsItemResourcesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterEphemeralReportSpecResultsItemResourcesItem", Builder]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecResultsItemResourcesItem,
            ClusterEphemeralReportSpecResultsItemResourcesItem.Builder,
        ]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    field_path: Annotated[str | None, Field(alias="fieldPath")] = None
    'If referring to a piece of an object instead of an entire object, this string\nshould contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].\nFor example, if the object reference is to a container within a pod, this would take on a value like:\n"spec.containers{name}" (where "name" refers to the name of the container that triggered\nthe event) or if no container name is specified "spec.containers[2]" (container with\nindex 2 in this pod). This syntax is chosen only to have some well-defined way of\nreferencing a part of an object.'
    kind: str | None = None
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
    resource_version: Annotated[str | None, Field(alias="resourceVersion")] = None
    "Specific resourceVersion to which this reference is made, if any.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"
    uid: str | None = None
    "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"


class ClusterEphemeralReportSpecResultsItemTimestamp(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpecResultsItemTimestamp"]:
            return ClusterEphemeralReportSpecResultsItemTimestamp

        def build(self) -> "ClusterEphemeralReportSpecResultsItemTimestamp":
            return ClusterEphemeralReportSpecResultsItemTimestamp(**self._attrs)

        def nanos(self, value: int, /) -> Self:
            "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive. This field may be limited in precision depending on context."
            return self._set("nanos", value)

        def seconds(self, value: int, /) -> Self:
            "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive."
            return self._set("seconds", value)

    class BuilderContext(
        BuilderContextBase["ClusterEphemeralReportSpecResultsItemTimestamp.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpecResultsItemTimestamp.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecResultsItemTimestamp."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterEphemeralReportSpecResultsItemTimestamp", Builder]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecResultsItemTimestamp,
            ClusterEphemeralReportSpecResultsItemTimestamp.Builder,
        ]()

    nanos: int
    "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive. This field may be limited in precision depending on context."
    seconds: int
    "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive."


class ClusterEphemeralReportSpecSummary(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpecSummary"]:
            return ClusterEphemeralReportSpecSummary

        def build(self) -> "ClusterEphemeralReportSpecSummary":
            return ClusterEphemeralReportSpecSummary(**self._attrs)

        def error(self, value: int | None, /) -> Self:
            "Error provides the count of policies that could not be evaluated"
            return self._set("error", value)

        def fail(self, value: int | None, /) -> Self:
            "Fail provides the count of policies whose requirements were not met"
            return self._set("fail", value)

        def pass_(self, value: int | None, /) -> Self:
            "Pass provides the count of policies whose requirements were met"
            return self._set("pass_", value)

        def skip(self, value: int | None, /) -> Self:
            "Skip indicates the count of policies that were not selected for evaluation"
            return self._set("skip", value)

        def warn(self, value: int | None, /) -> Self:
            "Warn provides the count of non-scored policies whose requirements were not met"
            return self._set("warn", value)

    class BuilderContext(BuilderContextBase["ClusterEphemeralReportSpecSummary.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpecSummary.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecSummary."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterEphemeralReportSpecSummary", Builder]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecSummary, ClusterEphemeralReportSpecSummary.Builder
        ]()

    error: int | None = None
    "Error provides the count of policies that could not be evaluated"
    fail: int | None = None
    "Fail provides the count of policies whose requirements were not met"
    pass_: Annotated[int | None, Field(alias="pass")] = None
    "Pass provides the count of policies whose requirements were met"
    skip: int | None = None
    "Skip indicates the count of policies that were not selected for evaluation"
    warn: int | None = None
    "Warn provides the count of non-scored policies whose requirements were not met"


class EphemeralReportSpecOwner(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpecOwner"]:
            return EphemeralReportSpecOwner

        def build(self) -> "EphemeralReportSpecOwner":
            return EphemeralReportSpecOwner(**self._attrs)

        def api_version(self, value: str, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def block_owner_deletion(self, value: bool | None, /) -> Self:
            'If true, AND if the owner has the "foregroundDeletion" finalizer, then\nthe owner cannot be deleted from the key-value store until this\nreference is removed.\nSee https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion\nfor how the garbage collector interacts with this field and enforces the foreground deletion.\nDefaults to false.\nTo set this field, a user needs "delete" permission of the owner,\notherwise 422 (Unprocessable Entity) will be returned.'
            return self._set("block_owner_deletion", value)

        def controller(self, value: bool | None, /) -> Self:
            "If true, this reference points to the managing controller."
            return self._set("controller", value)

        def kind(self, value: str, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str, /) -> Self:
            "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names"
            return self._set("name", value)

        def uid(self, value: str, /) -> Self:
            "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids"
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["EphemeralReportSpecOwner.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpecOwner.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecOwner."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EphemeralReportSpecOwner", Builder]:
        return GenericListBuilder[EphemeralReportSpecOwner, EphemeralReportSpecOwner.Builder]()

    api_version: Annotated[str, Field(alias="apiVersion")]
    "API version of the referent."
    block_owner_deletion: Annotated[bool | None, Field(alias="blockOwnerDeletion")] = None
    'If true, AND if the owner has the "foregroundDeletion" finalizer, then\nthe owner cannot be deleted from the key-value store until this\nreference is removed.\nSee https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion\nfor how the garbage collector interacts with this field and enforces the foreground deletion.\nDefaults to false.\nTo set this field, a user needs "delete" permission of the owner,\notherwise 422 (Unprocessable Entity) will be returned.'
    controller: bool | None = None
    "If true, this reference points to the managing controller."
    kind: str
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str
    "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names"
    uid: str
    "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids"


class EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem"]:
            return EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem

        def build(
            self,
        ) -> "EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem":
            return EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem(**self._attrs)

        def key(self, value: str, /) -> Self:
            "key is the label key that the selector applies to."
            return self._set("key", value)

        def operator(self, value: str, /) -> Self:
            "operator represents a key\u0027s relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist."
            return self._set("operator", value)

        def values(self, value: list[str] | None, /) -> Self:
            "values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch."
            return self._set("values", value)

    class BuilderContext(
        BuilderContextBase[
            "EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = (
                EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder()
            )
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem", Builder
    ]:
        return GenericListBuilder[
            EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem,
            EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder,
        ]()

    key: str
    "key is the label key that the selector applies to."
    operator: str
    "operator represents a key\u0027s relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist."
    values: list[str] | None = None
    "values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch."


class EphemeralReportSpecResultsItemResourcesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpecResultsItemResourcesItem"]:
            return EphemeralReportSpecResultsItemResourcesItem

        def build(self) -> "EphemeralReportSpecResultsItemResourcesItem":
            return EphemeralReportSpecResultsItemResourcesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def field_path(self, value: str | None, /) -> Self:
            'If referring to a piece of an object instead of an entire object, this string\nshould contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].\nFor example, if the object reference is to a container within a pod, this would take on a value like:\n"spec.containers{name}" (where "name" refers to the name of the container that triggered\nthe event) or if no container name is specified "spec.containers[2]" (container with\nindex 2 in this pod). This syntax is chosen only to have some well-defined way of\nreferencing a part of an object.'
            return self._set("field_path", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
            return self._set("namespace", value)

        def resource_version(self, value: str | None, /) -> Self:
            "Specific resourceVersion to which this reference is made, if any.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"
            return self._set("resource_version", value)

        def uid(self, value: str | None, /) -> Self:
            "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["EphemeralReportSpecResultsItemResourcesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpecResultsItemResourcesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecResultsItemResourcesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["EphemeralReportSpecResultsItemResourcesItem", Builder]:
        return GenericListBuilder[
            EphemeralReportSpecResultsItemResourcesItem,
            EphemeralReportSpecResultsItemResourcesItem.Builder,
        ]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    field_path: Annotated[str | None, Field(alias="fieldPath")] = None
    'If referring to a piece of an object instead of an entire object, this string\nshould contain a valid JSON/Go field access statement, such as desiredState.manifest.containers[2].\nFor example, if the object reference is to a container within a pod, this would take on a value like:\n"spec.containers{name}" (where "name" refers to the name of the container that triggered\nthe event) or if no container name is specified "spec.containers[2]" (container with\nindex 2 in this pod). This syntax is chosen only to have some well-defined way of\nreferencing a part of an object.'
    kind: str | None = None
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    name: str | None = None
    "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
    namespace: str | None = None
    "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/"
    resource_version: Annotated[str | None, Field(alias="resourceVersion")] = None
    "Specific resourceVersion to which this reference is made, if any.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"
    uid: str | None = None
    "UID of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#uids"


class EphemeralReportSpecResultsItemTimestamp(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpecResultsItemTimestamp"]:
            return EphemeralReportSpecResultsItemTimestamp

        def build(self) -> "EphemeralReportSpecResultsItemTimestamp":
            return EphemeralReportSpecResultsItemTimestamp(**self._attrs)

        def nanos(self, value: int, /) -> Self:
            "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive. This field may be limited in precision depending on context."
            return self._set("nanos", value)

        def seconds(self, value: int, /) -> Self:
            "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive."
            return self._set("seconds", value)

    class BuilderContext(BuilderContextBase["EphemeralReportSpecResultsItemTimestamp.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpecResultsItemTimestamp.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecResultsItemTimestamp."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["EphemeralReportSpecResultsItemTimestamp", Builder]:
        return GenericListBuilder[
            EphemeralReportSpecResultsItemTimestamp,
            EphemeralReportSpecResultsItemTimestamp.Builder,
        ]()

    nanos: int
    "Non-negative fractions of a second at nanosecond resolution. Negative\nsecond values with fractions must still have non-negative nanos values\nthat count forward in time. Must be from 0 to 999,999,999\ninclusive. This field may be limited in precision depending on context."
    seconds: int
    "Represents seconds of UTC time since Unix epoch\n1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to\n9999-12-31T23:59:59Z inclusive."


class EphemeralReportSpecSummary(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpecSummary"]:
            return EphemeralReportSpecSummary

        def build(self) -> "EphemeralReportSpecSummary":
            return EphemeralReportSpecSummary(**self._attrs)

        def error(self, value: int | None, /) -> Self:
            "Error provides the count of policies that could not be evaluated"
            return self._set("error", value)

        def fail(self, value: int | None, /) -> Self:
            "Fail provides the count of policies whose requirements were not met"
            return self._set("fail", value)

        def pass_(self, value: int | None, /) -> Self:
            "Pass provides the count of policies whose requirements were met"
            return self._set("pass_", value)

        def skip(self, value: int | None, /) -> Self:
            "Skip indicates the count of policies that were not selected for evaluation"
            return self._set("skip", value)

        def warn(self, value: int | None, /) -> Self:
            "Warn provides the count of non-scored policies whose requirements were not met"
            return self._set("warn", value)

    class BuilderContext(BuilderContextBase["EphemeralReportSpecSummary.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpecSummary.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecSummary."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EphemeralReportSpecSummary", Builder]:
        return GenericListBuilder[EphemeralReportSpecSummary, EphemeralReportSpecSummary.Builder]()

    error: int | None = None
    "Error provides the count of policies that could not be evaluated"
    fail: int | None = None
    "Fail provides the count of policies whose requirements were not met"
    pass_: Annotated[int | None, Field(alias="pass")] = None
    "Pass provides the count of policies whose requirements were met"
    skip: int | None = None
    "Skip indicates the count of policies that were not selected for evaluation"
    warn: int | None = None
    "Warn provides the count of non-scored policies whose requirements were not met"


class ClusterEphemeralReportSpecResultsItemResourceSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpecResultsItemResourceSelector"]:
            return ClusterEphemeralReportSpecResultsItemResourceSelector

        def build(self) -> "ClusterEphemeralReportSpecResultsItemResourceSelector":
            return ClusterEphemeralReportSpecResultsItemResourceSelector(**self._attrs)

        @overload
        def match_expressions(
            self,
            value_or_callback: (
                list[ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem]
                | None
            ),
            /,
        ) -> "ClusterEphemeralReportSpecResultsItemResourceSelector.Builder": ...

        @overload
        def match_expressions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem,
                        ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem,
                    ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder,
                ]
                | list[ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem],
            ],
            /,
        ) -> "ClusterEphemeralReportSpecResultsItemResourceSelector.Builder": ...

        @overload
        def match_expressions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[
            ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder
        ]: ...

        def match_expressions(self, value_or_callback=UNSET, /):
            "matchExpressions is a list of label selector requirements. The requirements are ANDed."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[
                    ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder
                ]()
                context._parent_builder = self
                context._field_name = "match_expressions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("match_expressions", value)

        def match_labels(self, value: dict[str, str] | None, /) -> Self:
            'matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.'
            return self._set("match_labels", value)

    class BuilderContext(
        BuilderContextBase["ClusterEphemeralReportSpecResultsItemResourceSelector.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpecResultsItemResourceSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecResultsItemResourceSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterEphemeralReportSpecResultsItemResourceSelector", Builder]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecResultsItemResourceSelector,
            ClusterEphemeralReportSpecResultsItemResourceSelector.Builder,
        ]()

    match_expressions: Annotated[
        list[ClusterEphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem] | None,
        Field(alias="matchExpressions"),
    ] = None
    "matchExpressions is a list of label selector requirements. The requirements are ANDed."
    match_labels: Annotated[dict[str, str] | None, Field(alias="matchLabels")] = None
    'matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.'


class EphemeralReportSpecResultsItemResourceSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpecResultsItemResourceSelector"]:
            return EphemeralReportSpecResultsItemResourceSelector

        def build(self) -> "EphemeralReportSpecResultsItemResourceSelector":
            return EphemeralReportSpecResultsItemResourceSelector(**self._attrs)

        @overload
        def match_expressions(
            self,
            value_or_callback: (
                list[EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem] | None
            ),
            /,
        ) -> "EphemeralReportSpecResultsItemResourceSelector.Builder": ...

        @overload
        def match_expressions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem,
                        EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem,
                    EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder,
                ]
                | list[EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem],
            ],
            /,
        ) -> "EphemeralReportSpecResultsItemResourceSelector.Builder": ...

        @overload
        def match_expressions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[
            EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder
        ]: ...

        def match_expressions(self, value_or_callback=UNSET, /):
            "matchExpressions is a list of label selector requirements. The requirements are ANDed."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[
                    EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.Builder
                ]()
                context._parent_builder = self
                context._field_name = "match_expressions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("match_expressions", value)

        def match_labels(self, value: dict[str, str] | None, /) -> Self:
            'matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.'
            return self._set("match_labels", value)

    class BuilderContext(
        BuilderContextBase["EphemeralReportSpecResultsItemResourceSelector.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpecResultsItemResourceSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecResultsItemResourceSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["EphemeralReportSpecResultsItemResourceSelector", Builder]:
        return GenericListBuilder[
            EphemeralReportSpecResultsItemResourceSelector,
            EphemeralReportSpecResultsItemResourceSelector.Builder,
        ]()

    match_expressions: Annotated[
        list[EphemeralReportSpecResultsItemResourceSelectorMatchExpressionsItem] | None,
        Field(alias="matchExpressions"),
    ] = None
    "matchExpressions is a list of label selector requirements. The requirements are ANDed."
    match_labels: Annotated[dict[str, str] | None, Field(alias="matchLabels")] = None
    'matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is "key", the\noperator is "In", and the values array contains only "value". The requirements are ANDed.'


class ClusterEphemeralReportSpecResultsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpecResultsItem"]:
            return ClusterEphemeralReportSpecResultsItem

        def build(self) -> "ClusterEphemeralReportSpecResultsItem":
            return ClusterEphemeralReportSpecResultsItem(**self._attrs)

        def category(self, value: str | None, /) -> Self:
            "Category indicates policy category"
            return self._set("category", value)

        def message(self, value: str | None, /) -> Self:
            "Description is a short user friendly message for the policy rule"
            return self._set("message", value)

        def policy(self, value: str, /) -> Self:
            "Policy is the name or identifier of the policy"
            return self._set("policy", value)

        def properties(self, value: dict[str, str] | None, /) -> Self:
            "Properties provides additional information for the policy rule"
            return self._set("properties", value)

        @overload
        def resource_selector(
            self,
            value_or_callback: (ClusterEphemeralReportSpecResultsItemResourceSelector | None),
            /,
        ) -> "ClusterEphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resource_selector(
            self,
            value_or_callback: Callable[
                [ClusterEphemeralReportSpecResultsItemResourceSelector.Builder],
                ClusterEphemeralReportSpecResultsItemResourceSelector.Builder
                | ClusterEphemeralReportSpecResultsItemResourceSelector,
            ],
            /,
        ) -> "ClusterEphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resource_selector(
            self, value_or_callback: Never = ...
        ) -> "ClusterEphemeralReportSpecResultsItemResourceSelector.BuilderContext": ...

        def resource_selector(self, value_or_callback=UNSET, /):
            "SubjectSelector is an optional label selector for checked Kubernetes resources.\nFor example, a policy result may apply to all pods that match a label.\nEither a Subject or a SubjectSelector can be specified.\nIf neither are provided, the result is assumed to be for the policy report scope."
            if self._in_context and value_or_callback is UNSET:
                context = ClusterEphemeralReportSpecResultsItemResourceSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ClusterEphemeralReportSpecResultsItemResourceSelector.builder()
                )
                if isinstance(
                    output,
                    ClusterEphemeralReportSpecResultsItemResourceSelector.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_selector", value)

        @overload
        def resources(
            self,
            value_or_callback: (list[ClusterEphemeralReportSpecResultsItemResourcesItem] | None),
            /,
        ) -> "ClusterEphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resources(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ClusterEphemeralReportSpecResultsItemResourcesItem,
                        ClusterEphemeralReportSpecResultsItemResourcesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ClusterEphemeralReportSpecResultsItemResourcesItem,
                    ClusterEphemeralReportSpecResultsItemResourcesItem.Builder,
                ]
                | list[ClusterEphemeralReportSpecResultsItemResourcesItem],
            ],
            /,
        ) -> "ClusterEphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resources(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ClusterEphemeralReportSpecResultsItemResourcesItem.Builder]: ...

        def resources(self, value_or_callback=UNSET, /):
            "Subjects is an optional reference to the checked Kubernetes resources"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[
                    ClusterEphemeralReportSpecResultsItemResourcesItem.Builder
                ]()
                context._parent_builder = self
                context._field_name = "resources"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    ClusterEphemeralReportSpecResultsItemResourcesItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("resources", value)

        def result(self, value: Literal["pass", "fail", "warn", "error", "skip"] | None, /) -> Self:
            "Result indicates the outcome of the policy rule execution"
            return self._set("result", value)

        def rule(self, value: str | None, /) -> Self:
            "Rule is the name or identifier of the rule within the policy"
            return self._set("rule", value)

        def scored(self, value: bool | None, /) -> Self:
            "Scored indicates if this result is scored"
            return self._set("scored", value)

        def severity(
            self, value: Literal["critical", "high", "low", "medium", "info"] | None, /
        ) -> Self:
            "Severity indicates policy check result criticality"
            return self._set("severity", value)

        def source(self, value: str | None, /) -> Self:
            "Source is an identifier for the policy engine that manages this report"
            return self._set("source", value)

        @overload
        def timestamp(
            self,
            value_or_callback: ClusterEphemeralReportSpecResultsItemTimestamp | None,
            /,
        ) -> "ClusterEphemeralReportSpecResultsItem.Builder": ...

        @overload
        def timestamp(
            self,
            value_or_callback: Callable[
                [ClusterEphemeralReportSpecResultsItemTimestamp.Builder],
                ClusterEphemeralReportSpecResultsItemTimestamp.Builder
                | ClusterEphemeralReportSpecResultsItemTimestamp,
            ],
            /,
        ) -> "ClusterEphemeralReportSpecResultsItem.Builder": ...

        @overload
        def timestamp(
            self, value_or_callback: Never = ...
        ) -> "ClusterEphemeralReportSpecResultsItemTimestamp.BuilderContext": ...

        def timestamp(self, value_or_callback=UNSET, /):
            "Timestamp indicates the time the result was found"
            if self._in_context and value_or_callback is UNSET:
                context = ClusterEphemeralReportSpecResultsItemTimestamp.BuilderContext()
                context._parent_builder = self
                context._field_name = "timestamp"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterEphemeralReportSpecResultsItemTimestamp.builder())
                if isinstance(output, ClusterEphemeralReportSpecResultsItemTimestamp.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("timestamp", value)

    class BuilderContext(BuilderContextBase["ClusterEphemeralReportSpecResultsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpecResultsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpecResultsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["ClusterEphemeralReportSpecResultsItem", Builder]:
        return GenericListBuilder[
            ClusterEphemeralReportSpecResultsItem,
            ClusterEphemeralReportSpecResultsItem.Builder,
        ]()

    category: str | None = None
    "Category indicates policy category"
    message: str | None = None
    "Description is a short user friendly message for the policy rule"
    policy: str
    "Policy is the name or identifier of the policy"
    properties: dict[str, str] | None = None
    "Properties provides additional information for the policy rule"
    resource_selector: Annotated[
        ClusterEphemeralReportSpecResultsItemResourceSelector | None,
        Field(alias="resourceSelector"),
    ] = None
    "SubjectSelector is an optional label selector for checked Kubernetes resources.\nFor example, a policy result may apply to all pods that match a label.\nEither a Subject or a SubjectSelector can be specified.\nIf neither are provided, the result is assumed to be for the policy report scope."
    resources: list[ClusterEphemeralReportSpecResultsItemResourcesItem] | None = None
    "Subjects is an optional reference to the checked Kubernetes resources"
    result: Literal["pass", "fail", "warn", "error", "skip"] | None = None
    "Result indicates the outcome of the policy rule execution"
    rule: str | None = None
    "Rule is the name or identifier of the rule within the policy"
    scored: bool | None = None
    "Scored indicates if this result is scored"
    severity: Literal["critical", "high", "low", "medium", "info"] | None = None
    "Severity indicates policy check result criticality"
    source: str | None = None
    "Source is an identifier for the policy engine that manages this report"
    timestamp: ClusterEphemeralReportSpecResultsItemTimestamp | None = None
    "Timestamp indicates the time the result was found"


class EphemeralReportSpecResultsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpecResultsItem"]:
            return EphemeralReportSpecResultsItem

        def build(self) -> "EphemeralReportSpecResultsItem":
            return EphemeralReportSpecResultsItem(**self._attrs)

        def category(self, value: str | None, /) -> Self:
            "Category indicates policy category"
            return self._set("category", value)

        def message(self, value: str | None, /) -> Self:
            "Description is a short user friendly message for the policy rule"
            return self._set("message", value)

        def policy(self, value: str, /) -> Self:
            "Policy is the name or identifier of the policy"
            return self._set("policy", value)

        def properties(self, value: dict[str, str] | None, /) -> Self:
            "Properties provides additional information for the policy rule"
            return self._set("properties", value)

        @overload
        def resource_selector(
            self,
            value_or_callback: EphemeralReportSpecResultsItemResourceSelector | None,
            /,
        ) -> "EphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resource_selector(
            self,
            value_or_callback: Callable[
                [EphemeralReportSpecResultsItemResourceSelector.Builder],
                EphemeralReportSpecResultsItemResourceSelector.Builder
                | EphemeralReportSpecResultsItemResourceSelector,
            ],
            /,
        ) -> "EphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resource_selector(
            self, value_or_callback: Never = ...
        ) -> "EphemeralReportSpecResultsItemResourceSelector.BuilderContext": ...

        def resource_selector(self, value_or_callback=UNSET, /):
            "SubjectSelector is an optional label selector for checked Kubernetes resources.\nFor example, a policy result may apply to all pods that match a label.\nEither a Subject or a SubjectSelector can be specified.\nIf neither are provided, the result is assumed to be for the policy report scope."
            if self._in_context and value_or_callback is UNSET:
                context = EphemeralReportSpecResultsItemResourceSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EphemeralReportSpecResultsItemResourceSelector.builder())
                if isinstance(output, EphemeralReportSpecResultsItemResourceSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_selector", value)

        @overload
        def resources(
            self,
            value_or_callback: list[EphemeralReportSpecResultsItemResourcesItem] | None,
            /,
        ) -> "EphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resources(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        EphemeralReportSpecResultsItemResourcesItem,
                        EphemeralReportSpecResultsItemResourcesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    EphemeralReportSpecResultsItemResourcesItem,
                    EphemeralReportSpecResultsItemResourcesItem.Builder,
                ]
                | list[EphemeralReportSpecResultsItemResourcesItem],
            ],
            /,
        ) -> "EphemeralReportSpecResultsItem.Builder": ...

        @overload
        def resources(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[EphemeralReportSpecResultsItemResourcesItem.Builder]: ...

        def resources(self, value_or_callback=UNSET, /):
            "Subjects is an optional reference to the checked Kubernetes resources"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[EphemeralReportSpecResultsItemResourcesItem.Builder]()
                context._parent_builder = self
                context._field_name = "resources"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    EphemeralReportSpecResultsItemResourcesItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("resources", value)

        def result(self, value: Literal["pass", "fail", "warn", "error", "skip"] | None, /) -> Self:
            "Result indicates the outcome of the policy rule execution"
            return self._set("result", value)

        def rule(self, value: str | None, /) -> Self:
            "Rule is the name or identifier of the rule within the policy"
            return self._set("rule", value)

        def scored(self, value: bool | None, /) -> Self:
            "Scored indicates if this result is scored"
            return self._set("scored", value)

        def severity(
            self, value: Literal["critical", "high", "low", "medium", "info"] | None, /
        ) -> Self:
            "Severity indicates policy check result criticality"
            return self._set("severity", value)

        def source(self, value: str | None, /) -> Self:
            "Source is an identifier for the policy engine that manages this report"
            return self._set("source", value)

        @overload
        def timestamp(
            self, value_or_callback: EphemeralReportSpecResultsItemTimestamp | None, /
        ) -> "EphemeralReportSpecResultsItem.Builder": ...

        @overload
        def timestamp(
            self,
            value_or_callback: Callable[
                [EphemeralReportSpecResultsItemTimestamp.Builder],
                EphemeralReportSpecResultsItemTimestamp.Builder
                | EphemeralReportSpecResultsItemTimestamp,
            ],
            /,
        ) -> "EphemeralReportSpecResultsItem.Builder": ...

        @overload
        def timestamp(
            self, value_or_callback: Never = ...
        ) -> "EphemeralReportSpecResultsItemTimestamp.BuilderContext": ...

        def timestamp(self, value_or_callback=UNSET, /):
            "Timestamp indicates the time the result was found"
            if self._in_context and value_or_callback is UNSET:
                context = EphemeralReportSpecResultsItemTimestamp.BuilderContext()
                context._parent_builder = self
                context._field_name = "timestamp"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EphemeralReportSpecResultsItemTimestamp.builder())
                if isinstance(output, EphemeralReportSpecResultsItemTimestamp.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("timestamp", value)

    class BuilderContext(BuilderContextBase["EphemeralReportSpecResultsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpecResultsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpecResultsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["EphemeralReportSpecResultsItem", Builder]:
        return GenericListBuilder[
            EphemeralReportSpecResultsItem, EphemeralReportSpecResultsItem.Builder
        ]()

    category: str | None = None
    "Category indicates policy category"
    message: str | None = None
    "Description is a short user friendly message for the policy rule"
    policy: str
    "Policy is the name or identifier of the policy"
    properties: dict[str, str] | None = None
    "Properties provides additional information for the policy rule"
    resource_selector: Annotated[
        EphemeralReportSpecResultsItemResourceSelector | None,
        Field(alias="resourceSelector"),
    ] = None
    "SubjectSelector is an optional label selector for checked Kubernetes resources.\nFor example, a policy result may apply to all pods that match a label.\nEither a Subject or a SubjectSelector can be specified.\nIf neither are provided, the result is assumed to be for the policy report scope."
    resources: list[EphemeralReportSpecResultsItemResourcesItem] | None = None
    "Subjects is an optional reference to the checked Kubernetes resources"
    result: Literal["pass", "fail", "warn", "error", "skip"] | None = None
    "Result indicates the outcome of the policy rule execution"
    rule: str | None = None
    "Rule is the name or identifier of the rule within the policy"
    scored: bool | None = None
    "Scored indicates if this result is scored"
    severity: Literal["critical", "high", "low", "medium", "info"] | None = None
    "Severity indicates policy check result criticality"
    source: str | None = None
    "Source is an identifier for the policy engine that manages this report"
    timestamp: EphemeralReportSpecResultsItemTimestamp | None = None
    "Timestamp indicates the time the result was found"


class ClusterEphemeralReportSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReportSpec"]:
            return ClusterEphemeralReportSpec

        def build(self) -> "ClusterEphemeralReportSpec":
            return ClusterEphemeralReportSpec(**self._attrs)

        @overload
        def owner(
            self, value_or_callback: ClusterEphemeralReportSpecOwner, /
        ) -> "ClusterEphemeralReportSpec.Builder": ...

        @overload
        def owner(
            self,
            value_or_callback: Callable[
                [ClusterEphemeralReportSpecOwner.Builder],
                ClusterEphemeralReportSpecOwner.Builder | ClusterEphemeralReportSpecOwner,
            ],
            /,
        ) -> "ClusterEphemeralReportSpec.Builder": ...

        @overload
        def owner(
            self, value_or_callback: Never = ...
        ) -> "ClusterEphemeralReportSpecOwner.BuilderContext": ...

        def owner(self, value_or_callback=UNSET, /):
            "Owner is a reference to the report owner (e.g. a Deployment, Namespace, or Node)"
            if self._in_context and value_or_callback is UNSET:
                context = ClusterEphemeralReportSpecOwner.BuilderContext()
                context._parent_builder = self
                context._field_name = "owner"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterEphemeralReportSpecOwner.builder())
                if isinstance(output, ClusterEphemeralReportSpecOwner.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("owner", value)

        @overload
        def results(
            self,
            value_or_callback: list[ClusterEphemeralReportSpecResultsItem] | None,
            /,
        ) -> "ClusterEphemeralReportSpec.Builder": ...

        @overload
        def results(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        ClusterEphemeralReportSpecResultsItem,
                        ClusterEphemeralReportSpecResultsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    ClusterEphemeralReportSpecResultsItem,
                    ClusterEphemeralReportSpecResultsItem.Builder,
                ]
                | list[ClusterEphemeralReportSpecResultsItem],
            ],
            /,
        ) -> "ClusterEphemeralReportSpec.Builder": ...

        @overload
        def results(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[ClusterEphemeralReportSpecResultsItem.Builder]: ...

        def results(self, value_or_callback=UNSET, /):
            "PolicyReportResult provides result details"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[ClusterEphemeralReportSpecResultsItem.Builder]()
                context._parent_builder = self
                context._field_name = "results"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterEphemeralReportSpecResultsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("results", value)

        @overload
        def summary(
            self, value_or_callback: ClusterEphemeralReportSpecSummary | None, /
        ) -> "ClusterEphemeralReportSpec.Builder": ...

        @overload
        def summary(
            self,
            value_or_callback: Callable[
                [ClusterEphemeralReportSpecSummary.Builder],
                ClusterEphemeralReportSpecSummary.Builder | ClusterEphemeralReportSpecSummary,
            ],
            /,
        ) -> "ClusterEphemeralReportSpec.Builder": ...

        @overload
        def summary(
            self, value_or_callback: Never = ...
        ) -> "ClusterEphemeralReportSpecSummary.BuilderContext": ...

        def summary(self, value_or_callback=UNSET, /):
            "PolicyReportSummary provides a summary of results"
            if self._in_context and value_or_callback is UNSET:
                context = ClusterEphemeralReportSpecSummary.BuilderContext()
                context._parent_builder = self
                context._field_name = "summary"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterEphemeralReportSpecSummary.builder())
                if isinstance(output, ClusterEphemeralReportSpecSummary.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("summary", value)

    class BuilderContext(BuilderContextBase["ClusterEphemeralReportSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReportSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReportSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ClusterEphemeralReportSpec", Builder]:
        return GenericListBuilder[ClusterEphemeralReportSpec, ClusterEphemeralReportSpec.Builder]()

    owner: ClusterEphemeralReportSpecOwner
    "Owner is a reference to the report owner (e.g. a Deployment, Namespace, or Node)"
    results: list[ClusterEphemeralReportSpecResultsItem] | None = None
    "PolicyReportResult provides result details"
    summary: ClusterEphemeralReportSpecSummary | None = None
    "PolicyReportSummary provides a summary of results"


class EphemeralReportSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReportSpec"]:
            return EphemeralReportSpec

        def build(self) -> "EphemeralReportSpec":
            return EphemeralReportSpec(**self._attrs)

        @overload
        def owner(
            self, value_or_callback: EphemeralReportSpecOwner, /
        ) -> "EphemeralReportSpec.Builder": ...

        @overload
        def owner(
            self,
            value_or_callback: Callable[
                [EphemeralReportSpecOwner.Builder],
                EphemeralReportSpecOwner.Builder | EphemeralReportSpecOwner,
            ],
            /,
        ) -> "EphemeralReportSpec.Builder": ...

        @overload
        def owner(
            self, value_or_callback: Never = ...
        ) -> "EphemeralReportSpecOwner.BuilderContext": ...

        def owner(self, value_or_callback=UNSET, /):
            "Owner is a reference to the report owner (e.g. a Deployment, Namespace, or Node)"
            if self._in_context and value_or_callback is UNSET:
                context = EphemeralReportSpecOwner.BuilderContext()
                context._parent_builder = self
                context._field_name = "owner"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EphemeralReportSpecOwner.builder())
                if isinstance(output, EphemeralReportSpecOwner.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("owner", value)

        @overload
        def results(
            self, value_or_callback: list[EphemeralReportSpecResultsItem] | None, /
        ) -> "EphemeralReportSpec.Builder": ...

        @overload
        def results(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        EphemeralReportSpecResultsItem,
                        EphemeralReportSpecResultsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    EphemeralReportSpecResultsItem,
                    EphemeralReportSpecResultsItem.Builder,
                ]
                | list[EphemeralReportSpecResultsItem],
            ],
            /,
        ) -> "EphemeralReportSpec.Builder": ...

        @overload
        def results(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[EphemeralReportSpecResultsItem.Builder]: ...

        def results(self, value_or_callback=UNSET, /):
            "PolicyReportResult provides result details"
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[EphemeralReportSpecResultsItem.Builder]()
                context._parent_builder = self
                context._field_name = "results"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EphemeralReportSpecResultsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("results", value)

        @overload
        def summary(
            self, value_or_callback: EphemeralReportSpecSummary | None, /
        ) -> "EphemeralReportSpec.Builder": ...

        @overload
        def summary(
            self,
            value_or_callback: Callable[
                [EphemeralReportSpecSummary.Builder],
                EphemeralReportSpecSummary.Builder | EphemeralReportSpecSummary,
            ],
            /,
        ) -> "EphemeralReportSpec.Builder": ...

        @overload
        def summary(
            self, value_or_callback: Never = ...
        ) -> "EphemeralReportSpecSummary.BuilderContext": ...

        def summary(self, value_or_callback=UNSET, /):
            "PolicyReportSummary provides a summary of results"
            if self._in_context and value_or_callback is UNSET:
                context = EphemeralReportSpecSummary.BuilderContext()
                context._parent_builder = self
                context._field_name = "summary"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EphemeralReportSpecSummary.builder())
                if isinstance(output, EphemeralReportSpecSummary.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("summary", value)

    class BuilderContext(BuilderContextBase["EphemeralReportSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReportSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReportSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EphemeralReportSpec", Builder]:
        return GenericListBuilder[EphemeralReportSpec, EphemeralReportSpec.Builder]()

    owner: EphemeralReportSpecOwner
    "Owner is a reference to the report owner (e.g. a Deployment, Namespace, or Node)"
    results: list[EphemeralReportSpecResultsItem] | None = None
    "PolicyReportResult provides result details"
    summary: EphemeralReportSpecSummary | None = None
    "PolicyReportSummary provides a summary of results"


class ClusterEphemeralReport(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "clusterephemeralreports",
        "scope": "Cluster",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["ClusterEphemeralReport"]:
            return ClusterEphemeralReport

        def build(self) -> "ClusterEphemeralReport":
            return ClusterEphemeralReport(**self._attrs)

        def api_version(self, value: Literal["reports.kyverno.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["ClusterEphemeralReport"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "ClusterEphemeralReport.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "ClusterEphemeralReport.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: ClusterEphemeralReportSpec, /
        ) -> "ClusterEphemeralReport.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [ClusterEphemeralReportSpec.Builder],
                ClusterEphemeralReportSpec.Builder | ClusterEphemeralReportSpec,
            ],
            /,
        ) -> "ClusterEphemeralReport.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "ClusterEphemeralReportSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ClusterEphemeralReportSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ClusterEphemeralReportSpec.builder())
                if isinstance(output, ClusterEphemeralReportSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

    class BuilderContext(BuilderContextBase["ClusterEphemeralReport.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = ClusterEphemeralReport.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for ClusterEphemeralReport."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["ClusterEphemeralReport", Builder]:
        return GenericListBuilder[ClusterEphemeralReport, ClusterEphemeralReport.Builder]()

    api_version: Annotated[Literal["reports.kyverno.io/v1"], Field(alias="apiVersion")] = (
        "reports.kyverno.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["ClusterEphemeralReport"] = "ClusterEphemeralReport"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: ClusterEphemeralReportSpec


class EphemeralReport(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "ephemeralreports",
        "scope": "Namespaced",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EphemeralReport"]:
            return EphemeralReport

        def build(self) -> "EphemeralReport":
            return EphemeralReport(**self._attrs)

        def api_version(self, value: Literal["reports.kyverno.io/v1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["EphemeralReport"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "EphemeralReport.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "EphemeralReport.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: EphemeralReportSpec, /) -> "EphemeralReport.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [EphemeralReportSpec.Builder],
                EphemeralReportSpec.Builder | EphemeralReportSpec,
            ],
            /,
        ) -> "EphemeralReport.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "EphemeralReportSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = EphemeralReportSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(EphemeralReportSpec.builder())
                if isinstance(output, EphemeralReportSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

    class BuilderContext(BuilderContextBase["EphemeralReport.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EphemeralReport.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EphemeralReport."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EphemeralReport", Builder]:
        return GenericListBuilder[EphemeralReport, EphemeralReport.Builder]()

    api_version: Annotated[Literal["reports.kyverno.io/v1"], Field(alias="apiVersion")] = (
        "reports.kyverno.io/v1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["EphemeralReport"] = "EphemeralReport"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: EphemeralReportSpec
