# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.kyverno.reports.v1 import ClusterEphemeralReport as _Resource4
    from cloudcoil.models.kyverno.reports.v1 import EphemeralReport as _Resource8
    from cloudcoil.models.kyverno.v1 import ClusterPolicy as _Resource5
    from cloudcoil.models.kyverno.v1 import Policy as _Resource10
    from cloudcoil.models.kyverno.v1beta1 import UpdateRequest as _Resource15
    from cloudcoil.models.kyverno.v2 import CleanupPolicy as _Resource0
    from cloudcoil.models.kyverno.v2 import ClusterCleanupPolicy as _Resource2
    from cloudcoil.models.kyverno.v2 import PolicyException as _Resource12
    from cloudcoil.models.kyverno.v2 import UpdateRequest as _Resource16
    from cloudcoil.models.kyverno.v2alpha1 import GlobalContextEntry as _Resource9
    from cloudcoil.models.kyverno.v2beta1 import CleanupPolicy as _Resource1
    from cloudcoil.models.kyverno.v2beta1 import ClusterCleanupPolicy as _Resource3
    from cloudcoil.models.kyverno.v2beta1 import ClusterPolicy as _Resource6
    from cloudcoil.models.kyverno.v2beta1 import Policy as _Resource11
    from cloudcoil.models.kyverno.v2beta1 import PolicyException as _Resource13
    from cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2 import ClusterPolicyReport as _Resource7
    from cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2 import PolicyReport as _Resource14

_MODELS = {
    ("CleanupPolicy", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "CleanupPolicy"),
    ("CleanupPolicy", "kyverno.io/v2beta1"): ("cloudcoil.models.kyverno.v2beta1", "CleanupPolicy"),
    ("ClusterCleanupPolicy", "kyverno.io/v2"): (
        "cloudcoil.models.kyverno.v2",
        "ClusterCleanupPolicy",
    ),
    ("ClusterCleanupPolicy", "kyverno.io/v2beta1"): (
        "cloudcoil.models.kyverno.v2beta1",
        "ClusterCleanupPolicy",
    ),
    ("ClusterEphemeralReport", "reports.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.reports.v1",
        "ClusterEphemeralReport",
    ),
    ("ClusterEphemeralReport", ""): (
        "cloudcoil.models.kyverno.reports.v1",
        "ClusterEphemeralReport",
    ),
    ("ClusterPolicy", "kyverno.io/v1"): ("cloudcoil.models.kyverno.v1", "ClusterPolicy"),
    ("ClusterPolicy", "kyverno.io/v2beta1"): ("cloudcoil.models.kyverno.v2beta1", "ClusterPolicy"),
    ("ClusterPolicyReport", "wgpolicyk8s.io/v1alpha2"): (
        "cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2",
        "ClusterPolicyReport",
    ),
    ("ClusterPolicyReport", ""): (
        "cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2",
        "ClusterPolicyReport",
    ),
    ("EphemeralReport", "reports.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.reports.v1",
        "EphemeralReport",
    ),
    ("EphemeralReport", ""): ("cloudcoil.models.kyverno.reports.v1", "EphemeralReport"),
    ("GlobalContextEntry", "kyverno.io/v2alpha1"): (
        "cloudcoil.models.kyverno.v2alpha1",
        "GlobalContextEntry",
    ),
    ("GlobalContextEntry", ""): ("cloudcoil.models.kyverno.v2alpha1", "GlobalContextEntry"),
    ("Policy", "kyverno.io/v1"): ("cloudcoil.models.kyverno.v1", "Policy"),
    ("Policy", "kyverno.io/v2beta1"): ("cloudcoil.models.kyverno.v2beta1", "Policy"),
    ("PolicyException", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "PolicyException"),
    ("PolicyException", "kyverno.io/v2beta1"): (
        "cloudcoil.models.kyverno.v2beta1",
        "PolicyException",
    ),
    ("PolicyReport", "wgpolicyk8s.io/v1alpha2"): (
        "cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2",
        "PolicyReport",
    ),
    ("PolicyReport", ""): ("cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2", "PolicyReport"),
    ("UpdateRequest", "kyverno.io/v1beta1"): ("cloudcoil.models.kyverno.v1beta1", "UpdateRequest"),
    ("UpdateRequest", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "UpdateRequest"),
}


@overload
def get_model(
    kind: Literal["CleanupPolicy"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["CleanupPolicy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ClusterCleanupPolicy"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ClusterCleanupPolicy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["ClusterEphemeralReport"], *, api_version: Literal["reports.kyverno.io/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["ClusterEphemeralReport"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicy"], *, api_version: Literal["kyverno.io/v1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicyReport"], *, api_version: Literal["wgpolicyk8s.io/v1alpha2"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicyReport"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["EphemeralReport"], *, api_version: Literal["reports.kyverno.io/v1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["EphemeralReport"], *, api_version: Literal[""] = ""
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["GlobalContextEntry"], *, api_version: Literal["kyverno.io/v2alpha1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["GlobalContextEntry"], *, api_version: Literal[""] = ""
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["Policy"], *, api_version: Literal["kyverno.io/v1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["Policy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["PolicyReport"], *, api_version: Literal["wgpolicyk8s.io/v1alpha2"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["PolicyReport"], *, api_version: Literal[""] = ""
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["UpdateRequest"], *, api_version: Literal["kyverno.io/v1beta1"]
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["UpdateRequest"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource16]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
