# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.kyverno.policies.v1 import DeletingPolicy as _Resource8
    from cloudcoil.models.kyverno.policies.v1 import GeneratingPolicy as _Resource12
    from cloudcoil.models.kyverno.policies.v1 import ImageValidatingPolicy as _Resource18
    from cloudcoil.models.kyverno.policies.v1 import MutatingPolicy as _Resource21
    from cloudcoil.models.kyverno.policies.v1 import NamespacedDeletingPolicy as _Resource24
    from cloudcoil.models.kyverno.policies.v1 import NamespacedGeneratingPolicy as _Resource26
    from cloudcoil.models.kyverno.policies.v1 import NamespacedImageValidatingPolicy as _Resource28
    from cloudcoil.models.kyverno.policies.v1 import NamespacedMutatingPolicy as _Resource30
    from cloudcoil.models.kyverno.policies.v1 import NamespacedValidatingPolicy as _Resource32
    from cloudcoil.models.kyverno.policies.v1 import PolicyException as _Resource38
    from cloudcoil.models.kyverno.policies.v1 import ValidatingPolicy as _Resource43
    from cloudcoil.models.kyverno.policies.v1alpha1 import DeletingPolicy as _Resource9
    from cloudcoil.models.kyverno.policies.v1alpha1 import GeneratingPolicy as _Resource13
    from cloudcoil.models.kyverno.policies.v1alpha1 import ImageValidatingPolicy as _Resource19
    from cloudcoil.models.kyverno.policies.v1alpha1 import MutatingPolicy as _Resource22
    from cloudcoil.models.kyverno.policies.v1alpha1 import PolicyException as _Resource39
    from cloudcoil.models.kyverno.policies.v1alpha1 import ValidatingPolicy as _Resource44
    from cloudcoil.models.kyverno.policies.v1beta1 import DeletingPolicy as _Resource10
    from cloudcoil.models.kyverno.policies.v1beta1 import GeneratingPolicy as _Resource14
    from cloudcoil.models.kyverno.policies.v1beta1 import ImageValidatingPolicy as _Resource20
    from cloudcoil.models.kyverno.policies.v1beta1 import MutatingPolicy as _Resource23
    from cloudcoil.models.kyverno.policies.v1beta1 import NamespacedDeletingPolicy as _Resource25
    from cloudcoil.models.kyverno.policies.v1beta1 import NamespacedGeneratingPolicy as _Resource27
    from cloudcoil.models.kyverno.policies.v1beta1 import (
        NamespacedImageValidatingPolicy as _Resource29,
    )
    from cloudcoil.models.kyverno.policies.v1beta1 import NamespacedMutatingPolicy as _Resource31
    from cloudcoil.models.kyverno.policies.v1beta1 import NamespacedValidatingPolicy as _Resource33
    from cloudcoil.models.kyverno.policies.v1beta1 import PolicyException as _Resource40
    from cloudcoil.models.kyverno.policies.v1beta1 import ValidatingPolicy as _Resource45
    from cloudcoil.models.kyverno.reports.v1 import ClusterEphemeralReport as _Resource4
    from cloudcoil.models.kyverno.reports.v1 import EphemeralReport as _Resource11
    from cloudcoil.models.kyverno.v1 import ClusterPolicy as _Resource5
    from cloudcoil.models.kyverno.v1 import Policy as _Resource34
    from cloudcoil.models.kyverno.v2 import CleanupPolicy as _Resource0
    from cloudcoil.models.kyverno.v2 import ClusterCleanupPolicy as _Resource2
    from cloudcoil.models.kyverno.v2 import GlobalContextEntry as _Resource15
    from cloudcoil.models.kyverno.v2 import PolicyException as _Resource36
    from cloudcoil.models.kyverno.v2 import UpdateRequest as _Resource42
    from cloudcoil.models.kyverno.v2alpha1 import GlobalContextEntry as _Resource16
    from cloudcoil.models.kyverno.v2beta1 import CleanupPolicy as _Resource1
    from cloudcoil.models.kyverno.v2beta1 import ClusterCleanupPolicy as _Resource3
    from cloudcoil.models.kyverno.v2beta1 import ClusterPolicy as _Resource6
    from cloudcoil.models.kyverno.v2beta1 import GlobalContextEntry as _Resource17
    from cloudcoil.models.kyverno.v2beta1 import Policy as _Resource35
    from cloudcoil.models.kyverno.v2beta1 import PolicyException as _Resource37
    from cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2 import ClusterPolicyReport as _Resource7
    from cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2 import PolicyReport as _Resource41

_MODELS = {
    ("CleanupPolicy", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "CleanupPolicy"),
    ("CleanupPolicy", "kyverno.io/v2beta1"): ("cloudcoil.models.kyverno.v2beta1", "CleanupPolicy"),
    ("ClusterCleanupPolicy", "kyverno.io/v2"): (
        "cloudcoil.models.kyverno.v2",
        "ClusterCleanupPolicy",
    ),
    ("ClusterCleanupPolicy", "kyverno.io/v2beta1"): (
        "cloudcoil.models.kyverno.v2beta1",
        "ClusterCleanupPolicy",
    ),
    ("ClusterEphemeralReport", "reports.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.reports.v1",
        "ClusterEphemeralReport",
    ),
    ("ClusterEphemeralReport", ""): (
        "cloudcoil.models.kyverno.reports.v1",
        "ClusterEphemeralReport",
    ),
    ("ClusterPolicy", "kyverno.io/v1"): ("cloudcoil.models.kyverno.v1", "ClusterPolicy"),
    ("ClusterPolicy", "kyverno.io/v2beta1"): ("cloudcoil.models.kyverno.v2beta1", "ClusterPolicy"),
    ("ClusterPolicyReport", "wgpolicyk8s.io/v1alpha2"): (
        "cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2",
        "ClusterPolicyReport",
    ),
    ("ClusterPolicyReport", ""): (
        "cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2",
        "ClusterPolicyReport",
    ),
    ("DeletingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "DeletingPolicy",
    ),
    ("DeletingPolicy", "policies.kyverno.io/v1alpha1"): (
        "cloudcoil.models.kyverno.policies.v1alpha1",
        "DeletingPolicy",
    ),
    ("DeletingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "DeletingPolicy",
    ),
    ("EphemeralReport", "reports.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.reports.v1",
        "EphemeralReport",
    ),
    ("EphemeralReport", ""): ("cloudcoil.models.kyverno.reports.v1", "EphemeralReport"),
    ("GeneratingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "GeneratingPolicy",
    ),
    ("GeneratingPolicy", "policies.kyverno.io/v1alpha1"): (
        "cloudcoil.models.kyverno.policies.v1alpha1",
        "GeneratingPolicy",
    ),
    ("GeneratingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "GeneratingPolicy",
    ),
    ("GlobalContextEntry", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "GlobalContextEntry"),
    ("GlobalContextEntry", "kyverno.io/v2alpha1"): (
        "cloudcoil.models.kyverno.v2alpha1",
        "GlobalContextEntry",
    ),
    ("GlobalContextEntry", "kyverno.io/v2beta1"): (
        "cloudcoil.models.kyverno.v2beta1",
        "GlobalContextEntry",
    ),
    ("ImageValidatingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "ImageValidatingPolicy",
    ),
    ("ImageValidatingPolicy", "policies.kyverno.io/v1alpha1"): (
        "cloudcoil.models.kyverno.policies.v1alpha1",
        "ImageValidatingPolicy",
    ),
    ("ImageValidatingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "ImageValidatingPolicy",
    ),
    ("MutatingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "MutatingPolicy",
    ),
    ("MutatingPolicy", "policies.kyverno.io/v1alpha1"): (
        "cloudcoil.models.kyverno.policies.v1alpha1",
        "MutatingPolicy",
    ),
    ("MutatingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "MutatingPolicy",
    ),
    ("NamespacedDeletingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "NamespacedDeletingPolicy",
    ),
    ("NamespacedDeletingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "NamespacedDeletingPolicy",
    ),
    ("NamespacedGeneratingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "NamespacedGeneratingPolicy",
    ),
    ("NamespacedGeneratingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "NamespacedGeneratingPolicy",
    ),
    ("NamespacedImageValidatingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "NamespacedImageValidatingPolicy",
    ),
    ("NamespacedImageValidatingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "NamespacedImageValidatingPolicy",
    ),
    ("NamespacedMutatingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "NamespacedMutatingPolicy",
    ),
    ("NamespacedMutatingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "NamespacedMutatingPolicy",
    ),
    ("NamespacedValidatingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "NamespacedValidatingPolicy",
    ),
    ("NamespacedValidatingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "NamespacedValidatingPolicy",
    ),
    ("Policy", "kyverno.io/v1"): ("cloudcoil.models.kyverno.v1", "Policy"),
    ("Policy", "kyverno.io/v2beta1"): ("cloudcoil.models.kyverno.v2beta1", "Policy"),
    ("PolicyException", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "PolicyException"),
    ("PolicyException", "kyverno.io/v2beta1"): (
        "cloudcoil.models.kyverno.v2beta1",
        "PolicyException",
    ),
    ("PolicyException", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "PolicyException",
    ),
    ("PolicyException", "policies.kyverno.io/v1alpha1"): (
        "cloudcoil.models.kyverno.policies.v1alpha1",
        "PolicyException",
    ),
    ("PolicyException", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "PolicyException",
    ),
    ("PolicyReport", "wgpolicyk8s.io/v1alpha2"): (
        "cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2",
        "PolicyReport",
    ),
    ("PolicyReport", ""): ("cloudcoil.models.kyverno.wgpolicyk8s_io.v1alpha2", "PolicyReport"),
    ("UpdateRequest", "kyverno.io/v2"): ("cloudcoil.models.kyverno.v2", "UpdateRequest"),
    ("UpdateRequest", ""): ("cloudcoil.models.kyverno.v2", "UpdateRequest"),
    ("ValidatingPolicy", "policies.kyverno.io/v1"): (
        "cloudcoil.models.kyverno.policies.v1",
        "ValidatingPolicy",
    ),
    ("ValidatingPolicy", "policies.kyverno.io/v1alpha1"): (
        "cloudcoil.models.kyverno.policies.v1alpha1",
        "ValidatingPolicy",
    ),
    ("ValidatingPolicy", "policies.kyverno.io/v1beta1"): (
        "cloudcoil.models.kyverno.policies.v1beta1",
        "ValidatingPolicy",
    ),
}


@overload
def get_model(
    kind: Literal["CleanupPolicy"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["CleanupPolicy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["ClusterCleanupPolicy"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["ClusterCleanupPolicy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["ClusterEphemeralReport"], *, api_version: Literal["reports.kyverno.io/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["ClusterEphemeralReport"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicy"], *, api_version: Literal["kyverno.io/v1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicyReport"], *, api_version: Literal["wgpolicyk8s.io/v1alpha2"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["ClusterPolicyReport"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["DeletingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["DeletingPolicy"], *, api_version: Literal["policies.kyverno.io/v1alpha1"]
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["DeletingPolicy"], *, api_version: Literal["policies.kyverno.io/v1beta1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["EphemeralReport"], *, api_version: Literal["reports.kyverno.io/v1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["EphemeralReport"], *, api_version: Literal[""] = ""
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["GeneratingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["GeneratingPolicy"], *, api_version: Literal["policies.kyverno.io/v1alpha1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["GeneratingPolicy"], *, api_version: Literal["policies.kyverno.io/v1beta1"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["GlobalContextEntry"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["GlobalContextEntry"], *, api_version: Literal["kyverno.io/v2alpha1"]
) -> type[_Resource16]: ...


@overload
def get_model(
    kind: Literal["GlobalContextEntry"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["ImageValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["ImageValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1alpha1"]
) -> type[_Resource19]: ...


@overload
def get_model(
    kind: Literal["ImageValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1beta1"]
) -> type[_Resource20]: ...


@overload
def get_model(
    kind: Literal["MutatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource21]: ...


@overload
def get_model(
    kind: Literal["MutatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1alpha1"]
) -> type[_Resource22]: ...


@overload
def get_model(
    kind: Literal["MutatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1beta1"]
) -> type[_Resource23]: ...


@overload
def get_model(
    kind: Literal["NamespacedDeletingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource24]: ...


@overload
def get_model(
    kind: Literal["NamespacedDeletingPolicy"],
    *,
    api_version: Literal["policies.kyverno.io/v1beta1"],
) -> type[_Resource25]: ...


@overload
def get_model(
    kind: Literal["NamespacedGeneratingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource26]: ...


@overload
def get_model(
    kind: Literal["NamespacedGeneratingPolicy"],
    *,
    api_version: Literal["policies.kyverno.io/v1beta1"],
) -> type[_Resource27]: ...


@overload
def get_model(
    kind: Literal["NamespacedImageValidatingPolicy"],
    *,
    api_version: Literal["policies.kyverno.io/v1"],
) -> type[_Resource28]: ...


@overload
def get_model(
    kind: Literal["NamespacedImageValidatingPolicy"],
    *,
    api_version: Literal["policies.kyverno.io/v1beta1"],
) -> type[_Resource29]: ...


@overload
def get_model(
    kind: Literal["NamespacedMutatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource30]: ...


@overload
def get_model(
    kind: Literal["NamespacedMutatingPolicy"],
    *,
    api_version: Literal["policies.kyverno.io/v1beta1"],
) -> type[_Resource31]: ...


@overload
def get_model(
    kind: Literal["NamespacedValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource32]: ...


@overload
def get_model(
    kind: Literal["NamespacedValidatingPolicy"],
    *,
    api_version: Literal["policies.kyverno.io/v1beta1"],
) -> type[_Resource33]: ...


@overload
def get_model(
    kind: Literal["Policy"], *, api_version: Literal["kyverno.io/v1"]
) -> type[_Resource34]: ...


@overload
def get_model(
    kind: Literal["Policy"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource35]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource36]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["kyverno.io/v2beta1"]
) -> type[_Resource37]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource38]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["policies.kyverno.io/v1alpha1"]
) -> type[_Resource39]: ...


@overload
def get_model(
    kind: Literal["PolicyException"], *, api_version: Literal["policies.kyverno.io/v1beta1"]
) -> type[_Resource40]: ...


@overload
def get_model(
    kind: Literal["PolicyReport"], *, api_version: Literal["wgpolicyk8s.io/v1alpha2"]
) -> type[_Resource41]: ...


@overload
def get_model(
    kind: Literal["PolicyReport"], *, api_version: Literal[""] = ""
) -> type[_Resource41]: ...


@overload
def get_model(
    kind: Literal["UpdateRequest"], *, api_version: Literal["kyverno.io/v2"]
) -> type[_Resource42]: ...


@overload
def get_model(
    kind: Literal["UpdateRequest"], *, api_version: Literal[""] = ""
) -> type[_Resource42]: ...


@overload
def get_model(
    kind: Literal["ValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1"]
) -> type[_Resource43]: ...


@overload
def get_model(
    kind: Literal["ValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1alpha1"]
) -> type[_Resource44]: ...


@overload
def get_model(
    kind: Literal["ValidatingPolicy"], *, api_version: Literal["policies.kyverno.io/v1beta1"]
) -> type[_Resource45]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
