# Generated by cloudcoil-model-codegen v0.7.0
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import Field


class UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind"]:
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind

        def build(
            self,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind":
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind(**self._attrs)

        def group(self, value: str, /) -> Self:
            return self._set("group", value)

        def kind(self, value: str, /) -> Self:
            return self._set("kind", value)

        def version(self, value: str, /) -> Self:
            return self._set("version", value)

    class BuilderContext(
        BuilderContextBase[
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.Builder()
            )
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind", Builder
    ]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind,
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.Builder,
        ]()

    group: str
    kind: str
    version: str


class UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind"]:
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind

        def build(
            self,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind":
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind(
                **self._attrs
            )

        def group(self, value: str, /) -> Self:
            return self._set("group", value)

        def kind(self, value: str, /) -> Self:
            return self._set("kind", value)

        def version(self, value: str, /) -> Self:
            return self._set("version", value)

    class BuilderContext(
        BuilderContextBase[
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.Builder()
            )
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind",
        Builder,
    ]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind,
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.Builder,
        ]()

    group: str
    kind: str
    version: str


class UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource"]:
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource

        def build(
            self,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource":
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource(
                **self._attrs
            )

        def group(self, value: str, /) -> Self:
            return self._set("group", value)

        def resource(self, value: str, /) -> Self:
            return self._set("resource", value)

        def version(self, value: str, /) -> Self:
            return self._set("version", value)

    class BuilderContext(
        BuilderContextBase[
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource",
        Builder,
    ]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource,
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.Builder,
        ]()

    group: str
    resource: str
    version: str


class UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource"]:
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource

        def build(
            self,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource":
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource(
                **self._attrs
            )

        def group(self, value: str, /) -> Self:
            return self._set("group", value)

        def resource(self, value: str, /) -> Self:
            return self._set("resource", value)

        def version(self, value: str, /) -> Self:
            return self._set("version", value)

    class BuilderContext(
        BuilderContextBase[
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.Builder()
            )
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource", Builder
    ]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource,
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.Builder,
        ]()

    group: str
    resource: str
    version: str


class UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo"]:
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo

        def build(
            self,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo":
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo(
                **self._attrs
            )

        def extra(self, value: dict[str, list[str]] | None, /) -> Self:
            "Any additional information provided by the authenticator."
            return self._set("extra", value)

        def groups(self, value: list[str] | None, /) -> Self:
            "The names of groups this user is a part of."
            return self._set("groups", value)

        def uid(self, value: str | None, /) -> Self:
            "A unique value that identifies this user across time. If this user is\ndeleted and another user by the same name is added, they will have\ndifferent UIDs."
            return self._set("uid", value)

        def username(self, value: str | None, /) -> Self:
            "The name that uniquely identifies this user among all active users."
            return self._set("username", value)

    class BuilderContext(
        BuilderContextBase[
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.Builder"
        ]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.Builder()
            )
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo", Builder
    ]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo,
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.Builder,
        ]()

    extra: dict[str, list[str]] | None = None
    "Any additional information provided by the authenticator."
    groups: list[str] | None = None
    "The names of groups this user is a part of."
    uid: str | None = None
    "A unique value that identifies this user across time. If this user is\ndeleted and another user by the same name is added, they will have\ndifferent UIDs."
    username: str | None = None
    "The name that uniquely identifies this user among all active users."


class UpdateRequestSpecContextUserInfoUserInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestSpecContextUserInfoUserInfo"]:
            return UpdateRequestSpecContextUserInfoUserInfo

        def build(self) -> "UpdateRequestSpecContextUserInfoUserInfo":
            return UpdateRequestSpecContextUserInfoUserInfo(**self._attrs)

        def extra(self, value: dict[str, list[str]] | None, /) -> Self:
            "Any additional information provided by the authenticator."
            return self._set("extra", value)

        def groups(self, value: list[str] | None, /) -> Self:
            "The names of groups this user is a part of."
            return self._set("groups", value)

        def uid(self, value: str | None, /) -> Self:
            "A unique value that identifies this user across time. If this user is\ndeleted and another user by the same name is added, they will have\ndifferent UIDs."
            return self._set("uid", value)

        def username(self, value: str | None, /) -> Self:
            "The name that uniquely identifies this user among all active users."
            return self._set("username", value)

    class BuilderContext(BuilderContextBase["UpdateRequestSpecContextUserInfoUserInfo.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecContextUserInfoUserInfo.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextUserInfoUserInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["UpdateRequestSpecContextUserInfoUserInfo", Builder]:
        return GenericListBuilder[
            UpdateRequestSpecContextUserInfoUserInfo,
            UpdateRequestSpecContextUserInfoUserInfo.Builder,
        ]()

    extra: dict[str, list[str]] | None = None
    "Any additional information provided by the authenticator."
    groups: list[str] | None = None
    "The names of groups this user is a part of."
    uid: str | None = None
    "A unique value that identifies this user across time. If this user is\ndeleted and another user by the same name is added, they will have\ndifferent UIDs."
    username: str | None = None
    "The name that uniquely identifies this user among all active users."


class UpdateRequestSpecResource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestSpecResource"]:
            return UpdateRequestSpecResource

        def build(self) -> "UpdateRequestSpecResource":
            return UpdateRequestSpecResource(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "APIVersion specifies resource apiVersion."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind specifies resource kind."
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name specifies the resource name."
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace specifies resource namespace."
            return self._set("namespace", value)

        def uid(self, value: str | None, /) -> Self:
            "UID specifies the resource uid."
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["UpdateRequestSpecResource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecResource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecResource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UpdateRequestSpecResource", Builder]:
        return GenericListBuilder[UpdateRequestSpecResource, UpdateRequestSpecResource.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "APIVersion specifies resource apiVersion."
    kind: str | None = None
    "Kind specifies resource kind."
    name: str | None = None
    "Name specifies the resource name."
    namespace: str | None = None
    "Namespace specifies resource namespace."
    uid: str | None = None
    "UID specifies the resource uid."


class UpdateRequestStatusGeneratedResourcesItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestStatusGeneratedResourcesItem"]:
            return UpdateRequestStatusGeneratedResourcesItem

        def build(self) -> "UpdateRequestStatusGeneratedResourcesItem":
            return UpdateRequestStatusGeneratedResourcesItem(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "APIVersion specifies resource apiVersion."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind specifies resource kind."
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name specifies the resource name."
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace specifies resource namespace."
            return self._set("namespace", value)

        def uid(self, value: str | None, /) -> Self:
            "UID specifies the resource uid."
            return self._set("uid", value)

    class BuilderContext(BuilderContextBase["UpdateRequestStatusGeneratedResourcesItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestStatusGeneratedResourcesItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestStatusGeneratedResourcesItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["UpdateRequestStatusGeneratedResourcesItem", Builder]:
        return GenericListBuilder[
            UpdateRequestStatusGeneratedResourcesItem,
            UpdateRequestStatusGeneratedResourcesItem.Builder,
        ]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "APIVersion specifies resource apiVersion."
    kind: str | None = None
    "Kind specifies resource kind."
    name: str | None = None
    "Name specifies the resource name."
    namespace: str | None = None
    "Namespace specifies resource namespace."
    uid: str | None = None
    "UID specifies the resource uid."


class UpdateRequestStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestStatus"]:
            return UpdateRequestStatus

        def build(self) -> "UpdateRequestStatus":
            return UpdateRequestStatus(**self._attrs)

        @overload
        def generated_resources(
            self,
            value_or_callback: list[UpdateRequestStatusGeneratedResourcesItem] | None,
            /,
        ) -> "UpdateRequestStatus.Builder": ...

        @overload
        def generated_resources(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        UpdateRequestStatusGeneratedResourcesItem,
                        UpdateRequestStatusGeneratedResourcesItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    UpdateRequestStatusGeneratedResourcesItem,
                    UpdateRequestStatusGeneratedResourcesItem.Builder,
                ]
                | list[UpdateRequestStatusGeneratedResourcesItem],
            ],
            /,
        ) -> "UpdateRequestStatus.Builder": ...

        @overload
        def generated_resources(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[UpdateRequestStatusGeneratedResourcesItem.Builder]: ...

        def generated_resources(self, value_or_callback=UNSET, /):
            "This will track the resources that are updated by the generate Policy.\nWill be used during clean up resources."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[UpdateRequestStatusGeneratedResourcesItem.Builder]()
                context._parent_builder = self
                context._field_name = "generated_resources"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestStatusGeneratedResourcesItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("generated_resources", value)

        def handler(self, value: str | None, /) -> Self:
            "Deprecated"
            return self._set("handler", value)

        def message(self, value: str | None, /) -> Self:
            "Specifies request status message."
            return self._set("message", value)

        def retry_count(self, value: int | None, /) -> Self:
            return self._set("retry_count", value)

        def state(self, value: str, /) -> Self:
            "State represents state of the update request."
            return self._set("state", value)

    class BuilderContext(BuilderContextBase["UpdateRequestStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UpdateRequestStatus", Builder]:
        return GenericListBuilder[UpdateRequestStatus, UpdateRequestStatus.Builder]()

    generated_resources: Annotated[
        list[UpdateRequestStatusGeneratedResourcesItem] | None,
        Field(alias="generatedResources"),
    ] = None
    "This will track the resources that are updated by the generate Policy.\nWill be used during clean up resources."
    handler: str | None = None
    "Deprecated"
    message: str | None = None
    "Specifies request status message."
    retry_count: Annotated[int | None, Field(alias="retryCount")] = None
    state: str
    "State represents state of the update request."


class UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(
            self,
        ) -> type["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest"]:
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest

        def build(
            self,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest":
            return UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest(**self._attrs)

        def dry_run(self, value: bool | None, /) -> Self:
            "DryRun indicates that modifications will definitely not be persisted for this request.\nDefaults to false."
            return self._set("dry_run", value)

        @overload
        def kind(
            self,
            value_or_callback: UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind,
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def kind(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.Builder],
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.Builder
                | UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind,
            ],
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def kind(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.BuilderContext": ...

        def kind(self, value_or_callback=UNSET, /):
            "Kind is the fully-qualified type of object being submitted (for example, v1.Pod or autoscaling.v1.Scale)"
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.BuilderContext()
                context._parent_builder = self
                context._field_name = "kind"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.builder()
                )
                if isinstance(
                    output,
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("kind", value)

        def name(self, value: str | None, /) -> Self:
            "Name is the name of the object as presented in the request.  On a CREATE operation, the client may omit name and\nrely on the server to generate the name.  If that is the case, this field will contain an empty string."
            return self._set("name", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace is the namespace associated with the request (if any)."
            return self._set("namespace", value)

        def object(self, value: dict[str, Any] | None, /) -> Self:
            "Object is the object from the incoming request."
            return self._set("object", value)

        def old_object(self, value: dict[str, Any] | None, /) -> Self:
            "OldObject is the existing object. Only populated for DELETE and UPDATE requests."
            return self._set("old_object", value)

        def operation(self, value: str, /) -> Self:
            "Operation is the operation being performed. This may be different than the operation\nrequested. e.g. a patch can result in either a CREATE or UPDATE Operation."
            return self._set("operation", value)

        def options(self, value: dict[str, Any] | None, /) -> Self:
            "Options is the operation option structure of the operation being performed.\ne.g. `meta.k8s.io/v1.DeleteOptions` or `meta.k8s.io/v1.CreateOptions`. This may be\ndifferent than the options the caller provided. e.g. for a patch request the performed\nOperation might be a CREATE, in which case the Options will a\n`meta.k8s.io/v1.CreateOptions` even though the caller provided `meta.k8s.io/v1.PatchOptions`."
            return self._set("options", value)

        @overload
        def request_kind(
            self,
            value_or_callback: (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind | None
            ),
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def request_kind(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.Builder],
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.Builder
                | UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind,
            ],
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def request_kind(
            self, value_or_callback: Never = ...
        ) -> (
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.BuilderContext"
        ): ...

        def request_kind(self, value_or_callback=UNSET, /):
            'RequestKind is the fully-qualified type of the original API request (for example, v1.Pod or autoscaling.v1.Scale).\nIf this is specified and differs from the value in "kind", an equivalent match and conversion was performed.\n\nFor example, if deployments can be modified via apps/v1 and apps/v1beta1, and a webhook registered a rule of\n`apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]` and `matchPolicy: Equivalent`,\nan API request to apps/v1beta1 deployments would be converted and sent to the webhook\nwith `kind: {group:"apps", version:"v1", kind:"Deployment"}` (matching the rule the webhook registered for),\nand `requestKind: {group:"apps", version:"v1beta1", kind:"Deployment"}` (indicating the kind of the original API request).\n\nSee documentation for the "matchPolicy" field in the webhook configuration type for more details.'
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.BuilderContext()
                context._parent_builder = self
                context._field_name = "request_kind"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.builder()
                )
                if isinstance(
                    output,
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("request_kind", value)

        @overload
        def request_resource(
            self,
            value_or_callback: (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource | None
            ),
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def request_resource(
            self,
            value_or_callback: Callable[
                [
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.Builder
                ],
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.Builder
                | UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource,
            ],
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def request_resource(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.BuilderContext": ...

        def request_resource(self, value_or_callback=UNSET, /):
            'RequestResource is the fully-qualified resource of the original API request (for example, v1.pods).\nIf this is specified and differs from the value in "resource", an equivalent match and conversion was performed.\n\nFor example, if deployments can be modified via apps/v1 and apps/v1beta1, and a webhook registered a rule of\n`apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]` and `matchPolicy: Equivalent`,\nan API request to apps/v1beta1 deployments would be converted and sent to the webhook\nwith `resource: {group:"apps", version:"v1", resource:"deployments"}` (matching the resource the webhook registered for),\nand `requestResource: {group:"apps", version:"v1beta1", resource:"deployments"}` (indicating the resource of the original API request).\n\nSee documentation for the "matchPolicy" field in the webhook configuration type.'
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.BuilderContext()
                context._parent_builder = self
                context._field_name = "request_resource"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.builder()
                )
                if isinstance(
                    output,
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("request_resource", value)

        def request_sub_resource(self, value: str | None, /) -> Self:
            'RequestSubResource is the name of the subresource of the original API request, if any (for example, "status" or "scale")\nIf this is specified and differs from the value in "subResource", an equivalent match and conversion was performed.\nSee documentation for the "matchPolicy" field in the webhook configuration type.'
            return self._set("request_sub_resource", value)

        @overload
        def resource(
            self,
            value_or_callback: UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource,
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def resource(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.Builder],
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.Builder
                | UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource,
            ],
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def resource(
            self, value_or_callback: Never = ...
        ) -> (
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.BuilderContext"
        ): ...

        def resource(self, value_or_callback=UNSET, /):
            "Resource is the fully-qualified resource being requested (for example, v1.pods)"
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.builder()
                )
                if isinstance(
                    output,
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("resource", value)

        def sub_resource(self, value: str | None, /) -> Self:
            'SubResource is the subresource being requested, if any (for example, "status" or "scale")'
            return self._set("sub_resource", value)

        def uid(self, value: str, /) -> Self:
            "UID is an identifier for the individual request/response. It allows us to distinguish instances of requests which are\notherwise identical (parallel requests, requests when earlier requests did not modify etc)\nThe UID is meant to track the round trip (request/response) between the KAS and the WebHook, not the user request.\nIt is suitable for correlating log entries between the webhook and apiserver, for either auditing or debugging."
            return self._set("uid", value)

        @overload
        def user_info(
            self,
            value_or_callback: UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo,
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def user_info(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.Builder],
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.Builder
                | UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo,
            ],
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder": ...

        @overload
        def user_info(
            self, value_or_callback: Never = ...
        ) -> (
            "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.BuilderContext"
        ): ...

        def user_info(self, value_or_callback=UNSET, /):
            "UserInfo is information about the requesting user"
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "user_info"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.builder()
                )
                if isinstance(
                    output,
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("user_info", value)

    class BuilderContext(
        BuilderContextBase["UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder[
        "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest", Builder
    ]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest,
            UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder,
        ]()

    dry_run: Annotated[bool | None, Field(alias="dryRun")] = None
    "DryRun indicates that modifications will definitely not be persisted for this request.\nDefaults to false."
    kind: UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestKind
    "Kind is the fully-qualified type of object being submitted (for example, v1.Pod or autoscaling.v1.Scale)"
    name: str | None = None
    "Name is the name of the object as presented in the request.  On a CREATE operation, the client may omit name and\nrely on the server to generate the name.  If that is the case, this field will contain an empty string."
    namespace: str | None = None
    "Namespace is the namespace associated with the request (if any)."
    object: dict[str, Any] | None = None
    "Object is the object from the incoming request."
    old_object: Annotated[dict[str, Any] | None, Field(alias="oldObject")] = None
    "OldObject is the existing object. Only populated for DELETE and UPDATE requests."
    operation: str
    "Operation is the operation being performed. This may be different than the operation\nrequested. e.g. a patch can result in either a CREATE or UPDATE Operation."
    options: dict[str, Any] | None = None
    "Options is the operation option structure of the operation being performed.\ne.g. `meta.k8s.io/v1.DeleteOptions` or `meta.k8s.io/v1.CreateOptions`. This may be\ndifferent than the options the caller provided. e.g. for a patch request the performed\nOperation might be a CREATE, in which case the Options will a\n`meta.k8s.io/v1.CreateOptions` even though the caller provided `meta.k8s.io/v1.PatchOptions`."
    request_kind: Annotated[
        UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestKind | None,
        Field(alias="requestKind"),
    ] = None
    'RequestKind is the fully-qualified type of the original API request (for example, v1.Pod or autoscaling.v1.Scale).\nIf this is specified and differs from the value in "kind", an equivalent match and conversion was performed.\n\nFor example, if deployments can be modified via apps/v1 and apps/v1beta1, and a webhook registered a rule of\n`apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]` and `matchPolicy: Equivalent`,\nan API request to apps/v1beta1 deployments would be converted and sent to the webhook\nwith `kind: {group:"apps", version:"v1", kind:"Deployment"}` (matching the rule the webhook registered for),\nand `requestKind: {group:"apps", version:"v1beta1", kind:"Deployment"}` (indicating the kind of the original API request).\n\nSee documentation for the "matchPolicy" field in the webhook configuration type for more details.'
    request_resource: Annotated[
        UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestRequestResource | None,
        Field(alias="requestResource"),
    ] = None
    'RequestResource is the fully-qualified resource of the original API request (for example, v1.pods).\nIf this is specified and differs from the value in "resource", an equivalent match and conversion was performed.\n\nFor example, if deployments can be modified via apps/v1 and apps/v1beta1, and a webhook registered a rule of\n`apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]` and `matchPolicy: Equivalent`,\nan API request to apps/v1beta1 deployments would be converted and sent to the webhook\nwith `resource: {group:"apps", version:"v1", resource:"deployments"}` (matching the resource the webhook registered for),\nand `requestResource: {group:"apps", version:"v1beta1", resource:"deployments"}` (indicating the resource of the original API request).\n\nSee documentation for the "matchPolicy" field in the webhook configuration type.'
    request_sub_resource: Annotated[str | None, Field(alias="requestSubResource")] = None
    'RequestSubResource is the name of the subresource of the original API request, if any (for example, "status" or "scale")\nIf this is specified and differs from the value in "subResource", an equivalent match and conversion was performed.\nSee documentation for the "matchPolicy" field in the webhook configuration type.'
    resource: UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestResource
    "Resource is the fully-qualified resource being requested (for example, v1.pods)"
    sub_resource: Annotated[str | None, Field(alias="subResource")] = None
    'SubResource is the subresource being requested, if any (for example, "status" or "scale")'
    uid: str
    "UID is an identifier for the individual request/response. It allows us to distinguish instances of requests which are\notherwise identical (parallel requests, requests when earlier requests did not modify etc)\nThe UID is meant to track the round trip (request/response) between the KAS and the WebHook, not the user request.\nIt is suitable for correlating log entries between the webhook and apiserver, for either auditing or debugging."
    user_info: Annotated[
        UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequestUserInfo,
        Field(alias="userInfo"),
    ]
    "UserInfo is information about the requesting user"


class UpdateRequestSpecContextUserInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestSpecContextUserInfo"]:
            return UpdateRequestSpecContextUserInfo

        def build(self) -> "UpdateRequestSpecContextUserInfo":
            return UpdateRequestSpecContextUserInfo(**self._attrs)

        def cluster_roles(self, value: list[str] | None, /) -> Self:
            "ClusterRoles is a list of possible clusterRoles send the request."
            return self._set("cluster_roles", value)

        def roles(self, value: list[str] | None, /) -> Self:
            "Roles is a list of possible role send the request."
            return self._set("roles", value)

        @overload
        def user_info(
            self, value_or_callback: UpdateRequestSpecContextUserInfoUserInfo | None, /
        ) -> "UpdateRequestSpecContextUserInfo.Builder": ...

        @overload
        def user_info(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextUserInfoUserInfo.Builder],
                UpdateRequestSpecContextUserInfoUserInfo.Builder
                | UpdateRequestSpecContextUserInfoUserInfo,
            ],
            /,
        ) -> "UpdateRequestSpecContextUserInfo.Builder": ...

        @overload
        def user_info(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContextUserInfoUserInfo.BuilderContext": ...

        def user_info(self, value_or_callback=UNSET, /):
            "UserInfo is the userInfo carried in the admission request."
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextUserInfoUserInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "user_info"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestSpecContextUserInfoUserInfo.builder())
                if isinstance(output, UpdateRequestSpecContextUserInfoUserInfo.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("user_info", value)

    class BuilderContext(BuilderContextBase["UpdateRequestSpecContextUserInfo.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecContextUserInfo.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextUserInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["UpdateRequestSpecContextUserInfo", Builder]:
        return GenericListBuilder[
            UpdateRequestSpecContextUserInfo, UpdateRequestSpecContextUserInfo.Builder
        ]()

    cluster_roles: Annotated[list[str] | None, Field(alias="clusterRoles")] = None
    "ClusterRoles is a list of possible clusterRoles send the request."
    roles: list[str] | None = None
    "Roles is a list of possible role send the request."
    user_info: Annotated[
        UpdateRequestSpecContextUserInfoUserInfo | None, Field(alias="userInfo")
    ] = None
    "UserInfo is the userInfo carried in the admission request."


class UpdateRequestSpecContextAdmissionRequestInfo(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestSpecContextAdmissionRequestInfo"]:
            return UpdateRequestSpecContextAdmissionRequestInfo

        def build(self) -> "UpdateRequestSpecContextAdmissionRequestInfo":
            return UpdateRequestSpecContextAdmissionRequestInfo(**self._attrs)

        @overload
        def admission_request(
            self,
            value_or_callback: (
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest | None
            ),
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfo.Builder": ...

        @overload
        def admission_request(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder],
                UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder
                | UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest,
            ],
            /,
        ) -> "UpdateRequestSpecContextAdmissionRequestInfo.Builder": ...

        @overload
        def admission_request(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.BuilderContext": ...

        def admission_request(self, value_or_callback=UNSET, /):
            "AdmissionRequest describes the admission.Attributes for the admission request."
            if self._in_context and value_or_callback is UNSET:
                context = (
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.BuilderContext()
                )
                context._parent_builder = self
                context._field_name = "admission_request"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.builder()
                )
                if isinstance(
                    output,
                    UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest.Builder,
                ):
                    value = output.build()
                else:
                    value = output
            return self._set("admission_request", value)

        def operation(self, value: str | None, /) -> Self:
            "Operation is the type of resource operation being checked for admission control"
            return self._set("operation", value)

    class BuilderContext(
        BuilderContextBase["UpdateRequestSpecContextAdmissionRequestInfo.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecContextAdmissionRequestInfo.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContextAdmissionRequestInfo."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["UpdateRequestSpecContextAdmissionRequestInfo", Builder]:
        return GenericListBuilder[
            UpdateRequestSpecContextAdmissionRequestInfo,
            UpdateRequestSpecContextAdmissionRequestInfo.Builder,
        ]()

    admission_request: Annotated[
        UpdateRequestSpecContextAdmissionRequestInfoAdmissionRequest | None,
        Field(alias="admissionRequest"),
    ] = None
    "AdmissionRequest describes the admission.Attributes for the admission request."
    operation: str | None = None
    "Operation is the type of resource operation being checked for admission control"


class UpdateRequestSpecContext(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestSpecContext"]:
            return UpdateRequestSpecContext

        def build(self) -> "UpdateRequestSpecContext":
            return UpdateRequestSpecContext(**self._attrs)

        @overload
        def admission_request_info(
            self,
            value_or_callback: UpdateRequestSpecContextAdmissionRequestInfo | None,
            /,
        ) -> "UpdateRequestSpecContext.Builder": ...

        @overload
        def admission_request_info(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextAdmissionRequestInfo.Builder],
                UpdateRequestSpecContextAdmissionRequestInfo.Builder
                | UpdateRequestSpecContextAdmissionRequestInfo,
            ],
            /,
        ) -> "UpdateRequestSpecContext.Builder": ...

        @overload
        def admission_request_info(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContextAdmissionRequestInfo.BuilderContext": ...

        def admission_request_info(self, value_or_callback=UNSET, /):
            "AdmissionRequestInfoObject stores the admission request and operation details"
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextAdmissionRequestInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "admission_request_info"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestSpecContextAdmissionRequestInfo.builder())
                if isinstance(output, UpdateRequestSpecContextAdmissionRequestInfo.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("admission_request_info", value)

        @overload
        def user_info(
            self, value_or_callback: UpdateRequestSpecContextUserInfo | None, /
        ) -> "UpdateRequestSpecContext.Builder": ...

        @overload
        def user_info(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContextUserInfo.Builder],
                UpdateRequestSpecContextUserInfo.Builder | UpdateRequestSpecContextUserInfo,
            ],
            /,
        ) -> "UpdateRequestSpecContext.Builder": ...

        @overload
        def user_info(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContextUserInfo.BuilderContext": ...

        def user_info(self, value_or_callback=UNSET, /):
            "RequestInfo contains permission info carried in an admission request."
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContextUserInfo.BuilderContext()
                context._parent_builder = self
                context._field_name = "user_info"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestSpecContextUserInfo.builder())
                if isinstance(output, UpdateRequestSpecContextUserInfo.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("user_info", value)

    class BuilderContext(BuilderContextBase["UpdateRequestSpecContext.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpecContext.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpecContext."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UpdateRequestSpecContext", Builder]:
        return GenericListBuilder[UpdateRequestSpecContext, UpdateRequestSpecContext.Builder]()

    admission_request_info: Annotated[
        UpdateRequestSpecContextAdmissionRequestInfo | None,
        Field(alias="admissionRequestInfo"),
    ] = None
    "AdmissionRequestInfoObject stores the admission request and operation details"
    user_info: Annotated[UpdateRequestSpecContextUserInfo | None, Field(alias="userInfo")] = None
    "RequestInfo contains permission info carried in an admission request."


class UpdateRequestSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequestSpec"]:
            return UpdateRequestSpec

        def build(self) -> "UpdateRequestSpec":
            return UpdateRequestSpec(**self._attrs)

        @overload
        def context(
            self, value_or_callback: UpdateRequestSpecContext, /
        ) -> "UpdateRequestSpec.Builder": ...

        @overload
        def context(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecContext.Builder],
                UpdateRequestSpecContext.Builder | UpdateRequestSpecContext,
            ],
            /,
        ) -> "UpdateRequestSpec.Builder": ...

        @overload
        def context(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecContext.BuilderContext": ...

        def context(self, value_or_callback=UNSET, /):
            "Context ..."
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecContext.BuilderContext()
                context._parent_builder = self
                context._field_name = "context"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestSpecContext.builder())
                if isinstance(output, UpdateRequestSpecContext.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("context", value)

        def delete_downstream(self, value: bool, /) -> Self:
            "DeleteDownstream represents whether the downstream needs to be deleted."
            return self._set("delete_downstream", value)

        def policy(self, value: str, /) -> Self:
            "Specifies the name of the policy."
            return self._set("policy", value)

        def request_type(self, value: Literal["mutate", "generate"] | None, /) -> Self:
            "Type represents request type for background processing"
            return self._set("request_type", value)

        @overload
        def resource(
            self, value_or_callback: UpdateRequestSpecResource, /
        ) -> "UpdateRequestSpec.Builder": ...

        @overload
        def resource(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpecResource.Builder],
                UpdateRequestSpecResource.Builder | UpdateRequestSpecResource,
            ],
            /,
        ) -> "UpdateRequestSpec.Builder": ...

        @overload
        def resource(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestSpecResource.BuilderContext": ...

        def resource(self, value_or_callback=UNSET, /):
            "ResourceSpec is the information to identify the trigger resource."
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpecResource.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestSpecResource.builder())
                if isinstance(output, UpdateRequestSpecResource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource", value)

        def rule(self, value: str, /) -> Self:
            "Rule is the associate rule name of the current UR."
            return self._set("rule", value)

        def synchronize(self, value: bool | None, /) -> Self:
            'Synchronize represents the sync behavior of the corresponding rule\nOptional. Defaults to "false" if not specified.'
            return self._set("synchronize", value)

    class BuilderContext(BuilderContextBase["UpdateRequestSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequestSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequestSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UpdateRequestSpec", Builder]:
        return GenericListBuilder[UpdateRequestSpec, UpdateRequestSpec.Builder]()

    context: UpdateRequestSpecContext
    "Context ..."
    delete_downstream: Annotated[bool, Field(alias="deleteDownstream")]
    "DeleteDownstream represents whether the downstream needs to be deleted."
    policy: str
    "Specifies the name of the policy."
    request_type: Annotated[Literal["mutate", "generate"] | None, Field(alias="requestType")] = None
    "Type represents request type for background processing"
    resource: UpdateRequestSpecResource
    "ResourceSpec is the information to identify the trigger resource."
    rule: str
    "Rule is the associate rule name of the current UR."
    synchronize: bool | None = None
    'Synchronize represents the sync behavior of the corresponding rule\nOptional. Defaults to "false" if not specified.'


class UpdateRequest(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "updaterequests",
        "scope": "Namespaced",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UpdateRequest"]:
            return UpdateRequest

        def build(self) -> "UpdateRequest":
            return UpdateRequest(**self._attrs)

        def api_version(self, value: Literal["kyverno.io/v1beta1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["UpdateRequest"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "UpdateRequest.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "UpdateRequest.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: UpdateRequestSpec | None, /
        ) -> "UpdateRequest.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [UpdateRequestSpec.Builder],
                UpdateRequestSpec.Builder | UpdateRequestSpec,
            ],
            /,
        ) -> "UpdateRequest.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "UpdateRequestSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestSpec.builder())
                if isinstance(output, UpdateRequestSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: UpdateRequestStatus | None, /
        ) -> "UpdateRequest.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [UpdateRequestStatus.Builder],
                UpdateRequestStatus.Builder | UpdateRequestStatus,
            ],
            /,
        ) -> "UpdateRequest.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "UpdateRequestStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = UpdateRequestStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UpdateRequestStatus.builder())
                if isinstance(output, UpdateRequestStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["UpdateRequest.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UpdateRequest.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UpdateRequest."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UpdateRequest", Builder]:
        return GenericListBuilder[UpdateRequest, UpdateRequest.Builder]()

    api_version: Annotated[Literal["kyverno.io/v1beta1"], Field(alias="apiVersion")] = (
        "kyverno.io/v1beta1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["UpdateRequest"] = "UpdateRequest"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: UpdateRequestSpec | None = None
    status: UpdateRequestStatus | None = None
