# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    cast,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseBuilder,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import AwareDatetime, Field, RootModel


class GlobalContextEntrySpecApiCallDataItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecApiCallDataItem"]:
            return GlobalContextEntrySpecApiCallDataItem

        def build(self) -> "GlobalContextEntrySpecApiCallDataItem":
            return GlobalContextEntrySpecApiCallDataItem(**self._attrs)

        def key(self, value: str, /) -> Self:
            "Key is a unique identifier for the data value"
            return self._set("key", value)

        def value(self, value: dict[str, Any], /) -> Self:
            "Value is the data value"
            return self._set("value", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecApiCallDataItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecApiCallDataItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecApiCallDataItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecApiCallDataItem", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecApiCallDataItem,
            GlobalContextEntrySpecApiCallDataItem.Builder,
        ]()

    key: str
    "Key is a unique identifier for the data value"
    value: dict[str, Any]
    "Value is the data value"


class GlobalContextEntrySpecApiCallServiceHeadersItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecApiCallServiceHeadersItem"]:
            return GlobalContextEntrySpecApiCallServiceHeadersItem

        def build(self) -> "GlobalContextEntrySpecApiCallServiceHeadersItem":
            return GlobalContextEntrySpecApiCallServiceHeadersItem(**self._attrs)

        def key(self, value: str, /) -> Self:
            "Key is the header key"
            return self._set("key", value)

        def value(self, value: str, /) -> Self:
            "Value is the header value"
            return self._set("value", value)

    class BuilderContext(
        BuilderContextBase["GlobalContextEntrySpecApiCallServiceHeadersItem.Builder"]
    ):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecApiCallServiceHeadersItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecApiCallServiceHeadersItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecApiCallServiceHeadersItem", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecApiCallServiceHeadersItem,
            GlobalContextEntrySpecApiCallServiceHeadersItem.Builder,
        ]()

    key: str
    "Key is the header key"
    value: str
    "Value is the header value"


class GlobalContextEntrySpecKubernetesResource(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecKubernetesResource"]:
            return GlobalContextEntrySpecKubernetesResource

        def build(self) -> "GlobalContextEntrySpecKubernetesResource":
            return GlobalContextEntrySpecKubernetesResource(**self._attrs)

        def group(self, value: str | None, /) -> Self:
            "Group defines the group of the resource."
            return self._set("group", value)

        def namespace(self, value: str | None, /) -> Self:
            "Namespace defines the namespace of the resource. Leave empty for cluster scoped resources.\nIf left empty for namespaced resources, all resources from all namespaces will be cached."
            return self._set("namespace", value)

        def resource(self, value: str, /) -> Self:
            'Resource defines the type of the resource.\nRequires the pluralized form of the resource kind in lowercase. (Ex., "deployments")'
            return self._set("resource", value)

        def version(self, value: str, /) -> Self:
            "Version defines the version of the resource."
            return self._set("version", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecKubernetesResource.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecKubernetesResource.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecKubernetesResource."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecKubernetesResource", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecKubernetesResource,
            GlobalContextEntrySpecKubernetesResource.Builder,
        ]()

    group: str | None = None
    "Group defines the group of the resource."
    namespace: str | None = None
    "Namespace defines the namespace of the resource. Leave empty for cluster scoped resources.\nIf left empty for namespaced resources, all resources from all namespaces will be cached."
    resource: str
    'Resource defines the type of the resource.\nRequires the pluralized form of the resource kind in lowercase. (Ex., "deployments")'
    version: str
    "Version defines the version of the resource."


class GlobalContextEntrySpecProjectionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecProjectionsItem"]:
            return GlobalContextEntrySpecProjectionsItem

        def build(self) -> "GlobalContextEntrySpecProjectionsItem":
            return GlobalContextEntrySpecProjectionsItem(**self._attrs)

        def jmes_path(self, value: str, /) -> Self:
            "JMESPath is the JMESPath expression to extract the value from the cached resource."
            return self._set("jmes_path", value)

        def name(self, value: str, /) -> Self:
            "Name is the name to use for the extracted value in the context."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecProjectionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecProjectionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecProjectionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecProjectionsItem", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecProjectionsItem,
            GlobalContextEntrySpecProjectionsItem.Builder,
        ]()

    jmes_path: Annotated[str, Field(alias="jmesPath")]
    "JMESPath is the JMESPath expression to extract the value from the cached resource."
    name: str
    "Name is the name to use for the extracted value in the context."


class GlobalContextEntryStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntryStatusConditionsItem"]:
            return GlobalContextEntryStatusConditionsItem

        def build(self) -> "GlobalContextEntryStatusConditionsItem":
            return GlobalContextEntryStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: AwareDatetime, /) -> Self:
            "lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
            return self._set("last_transition_time", value)

        def message(self, value: str, /) -> Self:
            "message is a human readable message indicating details about the transition.\nThis may be an empty string."
            return self._set("message", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
            return self._set("observed_generation", value)

        def reason(self, value: str, /) -> Self:
            "reason contains a programmatic identifier indicating the reason for the condition\u0027s last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty."
            return self._set("reason", value)

        def status(self, value: Literal["True", "False", "Unknown"], /) -> Self:
            "status of the condition, one of True, False, Unknown."
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "type of condition in CamelCase or in foo.example.com/CamelCase."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntryStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntryStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntryStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntryStatusConditionsItem", Builder]:
        return GenericListBuilder[
            GlobalContextEntryStatusConditionsItem,
            GlobalContextEntryStatusConditionsItem.Builder,
        ]()

    last_transition_time: Annotated[AwareDatetime, Field(alias="lastTransitionTime")]
    "lastTransitionTime is the last time the condition transitioned from one status to another.\nThis should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable."
    message: Annotated[str, Field(max_length=32768)]
    "message is a human readable message indicating details about the transition.\nThis may be an empty string."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration", ge=0)] = None
    "observedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
    reason: Annotated[
        str,
        Field(
            max_length=1024,
            min_length=1,
            pattern="^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$",
        ),
    ]
    "reason contains a programmatic identifier indicating the reason for the condition\u0027s last transition.\nProducers of specific condition types may define expected values and meanings for this field,\nand whether the values are considered a guaranteed API.\nThe value should be a CamelCase string.\nThis field may not be empty."
    status: Literal["True", "False", "Unknown"]
    "status of the condition, one of True, False, Unknown."
    type: Annotated[
        str,
        Field(
            max_length=316,
            pattern="^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$",
        ),
    ]
    "type of condition in CamelCase or in foo.example.com/CamelCase."


class GlobalContextEntryStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntryStatus"]:
            return GlobalContextEntryStatus

        def build(self) -> "GlobalContextEntryStatus":
            return GlobalContextEntryStatus(**self._attrs)

        @overload
        def conditions(
            self,
            value_or_callback: list[GlobalContextEntryStatusConditionsItem] | None,
            /,
        ) -> "GlobalContextEntryStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        GlobalContextEntryStatusConditionsItem,
                        GlobalContextEntryStatusConditionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    GlobalContextEntryStatusConditionsItem,
                    GlobalContextEntryStatusConditionsItem.Builder,
                ]
                | list[GlobalContextEntryStatusConditionsItem],
            ],
            /,
        ) -> "GlobalContextEntryStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[GlobalContextEntryStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[GlobalContextEntryStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntryStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

        def last_refresh_time(self, value: AwareDatetime | None, /) -> Self:
            "Indicates the time when the globalcontextentry was last refreshed successfully for the API Call"
            return self._set("last_refresh_time", value)

        def ready(self, value: bool | None, /) -> Self:
            "Deprecated in favor of Conditions"
            return self._set("ready", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntryStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntryStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntryStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["GlobalContextEntryStatus", Builder]:
        return GenericListBuilder[GlobalContextEntryStatus, GlobalContextEntryStatus.Builder]()

    conditions: list[GlobalContextEntryStatusConditionsItem] | None = None
    last_refresh_time: Annotated[AwareDatetime | None, Field(alias="lastRefreshTime")] = None
    "Indicates the time when the globalcontextentry was last refreshed successfully for the API Call"
    ready: bool | None = None
    "Deprecated in favor of Conditions"


class GlobalContextEntrySpecApiCallService(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecApiCallService"]:
            return GlobalContextEntrySpecApiCallService

        def build(self) -> "GlobalContextEntrySpecApiCallService":
            return GlobalContextEntrySpecApiCallService(**self._attrs)

        def ca_bundle(self, value: str | None, /) -> Self:
            "CABundle is a PEM encoded CA bundle which will be used to validate\nthe server certificate."
            return self._set("ca_bundle", value)

        @overload
        def headers(
            self,
            value_or_callback: (list[GlobalContextEntrySpecApiCallServiceHeadersItem] | None),
            /,
        ) -> "GlobalContextEntrySpecApiCallService.Builder": ...

        @overload
        def headers(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        GlobalContextEntrySpecApiCallServiceHeadersItem,
                        GlobalContextEntrySpecApiCallServiceHeadersItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    GlobalContextEntrySpecApiCallServiceHeadersItem,
                    GlobalContextEntrySpecApiCallServiceHeadersItem.Builder,
                ]
                | list[GlobalContextEntrySpecApiCallServiceHeadersItem],
            ],
            /,
        ) -> "GlobalContextEntrySpecApiCallService.Builder": ...

        @overload
        def headers(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[GlobalContextEntrySpecApiCallServiceHeadersItem.Builder]: ...

        def headers(self, value_or_callback=UNSET, /):
            "Headers is a list of optional HTTP headers to be included in the request."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[
                    GlobalContextEntrySpecApiCallServiceHeadersItem.Builder
                ]()
                context._parent_builder = self
                context._field_name = "headers"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(
                    GlobalContextEntrySpecApiCallServiceHeadersItem.list_builder()
                )
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("headers", value)

        def url(self, value: str, /) -> Self:
            "URL is the JSON web service URL. A typical form is\n`https://{service}.{namespace}:{port}/{path}`."
            return self._set("url", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecApiCallService.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecApiCallService.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecApiCallService."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecApiCallService", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecApiCallService,
            GlobalContextEntrySpecApiCallService.Builder,
        ]()

    ca_bundle: Annotated[str | None, Field(alias="caBundle")] = None
    "CABundle is a PEM encoded CA bundle which will be used to validate\nthe server certificate."
    headers: list[GlobalContextEntrySpecApiCallServiceHeadersItem] | None = None
    "Headers is a list of optional HTTP headers to be included in the request."
    url: str
    "URL is the JSON web service URL. A typical form is\n`https://{service}.{namespace}:{port}/{path}`."


class GlobalContextEntrySpecApiCall(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecApiCall"]:
            return GlobalContextEntrySpecApiCall

        def build(self) -> "GlobalContextEntrySpecApiCall":
            return GlobalContextEntrySpecApiCall(**self._attrs)

        @overload
        def data(
            self,
            value_or_callback: list[GlobalContextEntrySpecApiCallDataItem] | None,
            /,
        ) -> "GlobalContextEntrySpecApiCall.Builder": ...

        @overload
        def data(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        GlobalContextEntrySpecApiCallDataItem,
                        GlobalContextEntrySpecApiCallDataItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    GlobalContextEntrySpecApiCallDataItem,
                    GlobalContextEntrySpecApiCallDataItem.Builder,
                ]
                | list[GlobalContextEntrySpecApiCallDataItem],
            ],
            /,
        ) -> "GlobalContextEntrySpecApiCall.Builder": ...

        @overload
        def data(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[GlobalContextEntrySpecApiCallDataItem.Builder]: ...

        def data(self, value_or_callback=UNSET, /):
            "The data object specifies the POST data sent to the server.\nOnly applicable when the method field is set to POST."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[GlobalContextEntrySpecApiCallDataItem.Builder]()
                context._parent_builder = self
                context._field_name = "data"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecApiCallDataItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("data", value)

        def method(self, value: Literal["GET", "POST"] | None, /) -> Self:
            "Method is the HTTP request type (GET or POST). Defaults to GET."
            return self._set("method", value)

        def refresh_interval(self, value: str | None, /) -> Self:
            'RefreshInterval defines the interval in duration at which to poll the APICall.\nThe duration is a sequence of decimal numbers, each with optional fraction and a unit suffix,\nsuch as "300ms", "1.5h" or "2h45m". Valid time units are "ns", "us" (or "\u00b5s"), "ms", "s", "m", "h".'
            return self._set("refresh_interval", value)

        def retry_limit(self, value: int | None, /) -> Self:
            "RetryLimit defines the number of times the APICall should be retried in case of failure."
            return self._set("retry_limit", value)

        @overload
        def service(
            self, value_or_callback: GlobalContextEntrySpecApiCallService | None, /
        ) -> "GlobalContextEntrySpecApiCall.Builder": ...

        @overload
        def service(
            self,
            value_or_callback: Callable[
                [GlobalContextEntrySpecApiCallService.Builder],
                GlobalContextEntrySpecApiCallService.Builder | GlobalContextEntrySpecApiCallService,
            ],
            /,
        ) -> "GlobalContextEntrySpecApiCall.Builder": ...

        @overload
        def service(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntrySpecApiCallService.BuilderContext": ...

        def service(self, value_or_callback=UNSET, /):
            "Service is an API call to a JSON web service.\nThis is used for non-Kubernetes API server calls.\nIt\u0027s mutually exclusive with the URLPath field."
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntrySpecApiCallService.BuilderContext()
                context._parent_builder = self
                context._field_name = "service"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecApiCallService.builder())
                if isinstance(output, GlobalContextEntrySpecApiCallService.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("service", value)

        def url_path(self, value: str | None, /) -> Self:
            'URLPath is the URL path to be used in the HTTP GET or POST request to the\nKubernetes API server (e.g. "/api/v1/namespaces" or  "/apis/apps/v1/deployments").\nThe format required is the same format used by the `kubectl get --raw` command.\nSee https://kyverno.io/docs/writing-policies/external-data-sources/#variables-from-kubernetes-api-server-calls\nfor details.\nIt\u0027s mutually exclusive with the Service field.'
            return self._set("url_path", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecApiCall.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecApiCall.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecApiCall."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecApiCall", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecApiCall, GlobalContextEntrySpecApiCall.Builder
        ]()

    data: list[GlobalContextEntrySpecApiCallDataItem] | None = None
    "The data object specifies the POST data sent to the server.\nOnly applicable when the method field is set to POST."
    method: Literal["GET", "POST"] | None = "GET"
    "Method is the HTTP request type (GET or POST). Defaults to GET."
    refresh_interval: Annotated[str | None, Field(alias="refreshInterval")] = "10m"
    'RefreshInterval defines the interval in duration at which to poll the APICall.\nThe duration is a sequence of decimal numbers, each with optional fraction and a unit suffix,\nsuch as "300ms", "1.5h" or "2h45m". Valid time units are "ns", "us" (or "\u00b5s"), "ms", "s", "m", "h".'
    retry_limit: Annotated[int | None, Field(alias="retryLimit", ge=1)] = 3
    "RetryLimit defines the number of times the APICall should be retried in case of failure."
    service: GlobalContextEntrySpecApiCallService | None = None
    "Service is an API call to a JSON web service.\nThis is used for non-Kubernetes API server calls.\nIt\u0027s mutually exclusive with the URLPath field."
    url_path: Annotated[str | None, Field(alias="urlPath")] = None
    'URLPath is the URL path to be used in the HTTP GET or POST request to the\nKubernetes API server (e.g. "/api/v1/namespaces" or  "/apis/apps/v1/deployments").\nThe format required is the same format used by the `kubectl get --raw` command.\nSee https://kyverno.io/docs/writing-policies/external-data-sources/#variables-from-kubernetes-api-server-calls\nfor details.\nIt\u0027s mutually exclusive with the Service field.'


class GlobalContextEntrySpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpec"]:
            return GlobalContextEntrySpec

        def build(self) -> "GlobalContextEntrySpec":
            return GlobalContextEntrySpec(**self._attrs)

        @overload
        def api_call(
            self, value_or_callback: GlobalContextEntrySpecApiCall | None, /
        ) -> "GlobalContextEntrySpec.Builder": ...

        @overload
        def api_call(
            self,
            value_or_callback: Callable[
                [GlobalContextEntrySpecApiCall.Builder],
                GlobalContextEntrySpecApiCall.Builder | GlobalContextEntrySpecApiCall,
            ],
            /,
        ) -> "GlobalContextEntrySpec.Builder": ...

        @overload
        def api_call(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntrySpecApiCall.BuilderContext": ...

        def api_call(self, value_or_callback=UNSET, /):
            "Stores results from an API call which will be cached.\nMutually exclusive with KubernetesResource.\nThis can be used to make calls to external (non-Kubernetes API server) services.\nIt can also be used to make calls to the Kubernetes API server in such cases:\n1. A POST is needed to create a resource.\n2. Finer-grained control is needed. Example: To restrict the number of resources cached."
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntrySpecApiCall.BuilderContext()
                context._parent_builder = self
                context._field_name = "api_call"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecApiCall.builder())
                if isinstance(output, GlobalContextEntrySpecApiCall.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("api_call", value)

        @overload
        def kubernetes_resource(
            self, value_or_callback: GlobalContextEntrySpecKubernetesResource, /
        ) -> "GlobalContextEntrySpec.Builder": ...

        @overload
        def kubernetes_resource(
            self,
            value_or_callback: Callable[
                [GlobalContextEntrySpecKubernetesResource.Builder],
                GlobalContextEntrySpecKubernetesResource.Builder
                | GlobalContextEntrySpecKubernetesResource,
            ],
            /,
        ) -> "GlobalContextEntrySpec.Builder": ...

        @overload
        def kubernetes_resource(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntrySpecKubernetesResource.BuilderContext": ...

        def kubernetes_resource(self, value_or_callback=UNSET, /):
            "Stores a list of Kubernetes resources which will be cached.\nMutually exclusive with APICall."
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntrySpecKubernetesResource.BuilderContext()
                context._parent_builder = self
                context._field_name = "kubernetes_resource"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecKubernetesResource.builder())
                if isinstance(output, GlobalContextEntrySpecKubernetesResource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("kubernetes_resource", value)

        @overload
        def projections(
            self,
            value_or_callback: list[GlobalContextEntrySpecProjectionsItem] | None,
            /,
        ) -> "GlobalContextEntrySpec.Builder": ...

        @overload
        def projections(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        GlobalContextEntrySpecProjectionsItem,
                        GlobalContextEntrySpecProjectionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    GlobalContextEntrySpecProjectionsItem,
                    GlobalContextEntrySpecProjectionsItem.Builder,
                ]
                | list[GlobalContextEntrySpecProjectionsItem],
            ],
            /,
        ) -> "GlobalContextEntrySpec.Builder": ...

        @overload
        def projections(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[GlobalContextEntrySpecProjectionsItem.Builder]: ...

        def projections(self, value_or_callback=UNSET, /):
            "Projections defines the list of JMESPath expressions to extract values from the cached resource."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[GlobalContextEntrySpecProjectionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "projections"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecProjectionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("projections", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["GlobalContextEntrySpec", Builder]:
        return GenericListBuilder[GlobalContextEntrySpec, GlobalContextEntrySpec.Builder]()

    api_call: Annotated[GlobalContextEntrySpecApiCall | None, Field(alias="apiCall")] = None
    "Stores results from an API call which will be cached.\nMutually exclusive with KubernetesResource.\nThis can be used to make calls to external (non-Kubernetes API server) services.\nIt can also be used to make calls to the Kubernetes API server in such cases:\n1. A POST is needed to create a resource.\n2. Finer-grained control is needed. Example: To restrict the number of resources cached."
    kubernetes_resource: Annotated[
        GlobalContextEntrySpecKubernetesResource, Field(alias="kubernetesResource")
    ]
    "Stores a list of Kubernetes resources which will be cached.\nMutually exclusive with APICall."
    projections: list[GlobalContextEntrySpecProjectionsItem] | None = None
    "Projections defines the list of JMESPath expressions to extract values from the cached resource."


class GlobalContextEntrySpecModel(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntrySpecModel"]:
            return GlobalContextEntrySpecModel

        def build(self) -> "GlobalContextEntrySpecModel":
            return GlobalContextEntrySpecModel(**self._attrs)

        @overload
        def api_call(
            self, value_or_callback: GlobalContextEntrySpecApiCall, /
        ) -> "GlobalContextEntrySpecModel.Builder": ...

        @overload
        def api_call(
            self,
            value_or_callback: Callable[
                [GlobalContextEntrySpecApiCall.Builder],
                GlobalContextEntrySpecApiCall.Builder | GlobalContextEntrySpecApiCall,
            ],
            /,
        ) -> "GlobalContextEntrySpecModel.Builder": ...

        @overload
        def api_call(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntrySpecApiCall.BuilderContext": ...

        def api_call(self, value_or_callback=UNSET, /):
            "Stores results from an API call which will be cached.\nMutually exclusive with KubernetesResource.\nThis can be used to make calls to external (non-Kubernetes API server) services.\nIt can also be used to make calls to the Kubernetes API server in such cases:\n1. A POST is needed to create a resource.\n2. Finer-grained control is needed. Example: To restrict the number of resources cached."
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntrySpecApiCall.BuilderContext()
                context._parent_builder = self
                context._field_name = "api_call"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecApiCall.builder())
                if isinstance(output, GlobalContextEntrySpecApiCall.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("api_call", value)

        @overload
        def kubernetes_resource(
            self, value_or_callback: GlobalContextEntrySpecKubernetesResource | None, /
        ) -> "GlobalContextEntrySpecModel.Builder": ...

        @overload
        def kubernetes_resource(
            self,
            value_or_callback: Callable[
                [GlobalContextEntrySpecKubernetesResource.Builder],
                GlobalContextEntrySpecKubernetesResource.Builder
                | GlobalContextEntrySpecKubernetesResource,
            ],
            /,
        ) -> "GlobalContextEntrySpecModel.Builder": ...

        @overload
        def kubernetes_resource(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntrySpecKubernetesResource.BuilderContext": ...

        def kubernetes_resource(self, value_or_callback=UNSET, /):
            "Stores a list of Kubernetes resources which will be cached.\nMutually exclusive with APICall."
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntrySpecKubernetesResource.BuilderContext()
                context._parent_builder = self
                context._field_name = "kubernetes_resource"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecKubernetesResource.builder())
                if isinstance(output, GlobalContextEntrySpecKubernetesResource.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("kubernetes_resource", value)

        @overload
        def projections(
            self,
            value_or_callback: list[GlobalContextEntrySpecProjectionsItem] | None,
            /,
        ) -> "GlobalContextEntrySpecModel.Builder": ...

        @overload
        def projections(
            self,
            value_or_callback: Callable[
                [
                    GenericListBuilder[
                        GlobalContextEntrySpecProjectionsItem,
                        GlobalContextEntrySpecProjectionsItem.Builder,
                    ]
                ],
                GenericListBuilder[
                    GlobalContextEntrySpecProjectionsItem,
                    GlobalContextEntrySpecProjectionsItem.Builder,
                ]
                | list[GlobalContextEntrySpecProjectionsItem],
            ],
            /,
        ) -> "GlobalContextEntrySpecModel.Builder": ...

        @overload
        def projections(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[GlobalContextEntrySpecProjectionsItem.Builder]: ...

        def projections(self, value_or_callback=UNSET, /):
            "Projections defines the list of JMESPath expressions to extract values from the cached resource."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[GlobalContextEntrySpecProjectionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "projections"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecProjectionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("projections", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecModel.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecModel.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecModel."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["GlobalContextEntrySpecModel", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecModel, GlobalContextEntrySpecModel.Builder
        ]()

    api_call: Annotated[GlobalContextEntrySpecApiCall, Field(alias="apiCall")]
    "Stores results from an API call which will be cached.\nMutually exclusive with KubernetesResource.\nThis can be used to make calls to external (non-Kubernetes API server) services.\nIt can also be used to make calls to the Kubernetes API server in such cases:\n1. A POST is needed to create a resource.\n2. Finer-grained control is needed. Example: To restrict the number of resources cached."
    kubernetes_resource: Annotated[
        GlobalContextEntrySpecKubernetesResource | None,
        Field(alias="kubernetesResource"),
    ] = None
    "Stores a list of Kubernetes resources which will be cached.\nMutually exclusive with APICall."
    projections: list[GlobalContextEntrySpecProjectionsItem] | None = None
    "Projections defines the list of JMESPath expressions to extract values from the cached resource."


class GlobalContextEntrySpecModel1(RootModel[GlobalContextEntrySpec | GlobalContextEntrySpecModel]):
    class Builder(BaseBuilder):
        _value: GlobalContextEntrySpec | GlobalContextEntrySpecModel | None = None

        def root(self, value: GlobalContextEntrySpec | GlobalContextEntrySpecModel, /) -> Self:
            "Spec declares policy exception behaviors."
            builder = self if self._in_context else self.__class__()
            builder._value = value
            return builder

        def __call__(self, value: GlobalContextEntrySpec | GlobalContextEntrySpecModel, /) -> Self:
            "Spec declares policy exception behaviors."
            builder = self if self._in_context else self.__class__()
            builder._value = value
            return builder

        def build(self) -> "GlobalContextEntrySpecModel1":
            value = cast(GlobalContextEntrySpec | GlobalContextEntrySpecModel, self._value)
            return GlobalContextEntrySpecModel1(value)

    root: GlobalContextEntrySpec | GlobalContextEntrySpecModel
    "Spec declares policy exception behaviors."

    class BuilderContext(BuilderContextBase["GlobalContextEntrySpecModel1.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntrySpecModel1.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntrySpecModel1."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(
        cls,
    ) -> GenericListBuilder["GlobalContextEntrySpecModel1", Builder]:
        return GenericListBuilder[
            GlobalContextEntrySpecModel1, GlobalContextEntrySpecModel1.Builder
        ]()


class GlobalContextEntry(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "globalcontextentries",
        "scope": "Cluster",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["GlobalContextEntry"]:
            return GlobalContextEntry

        def build(self) -> "GlobalContextEntry":
            return GlobalContextEntry(**self._attrs)

        def api_version(self, value: Literal["kyverno.io/v2alpha1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["GlobalContextEntry"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "GlobalContextEntry.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "GlobalContextEntry.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(
            self, value_or_callback: GlobalContextEntrySpecModel1, /
        ) -> "GlobalContextEntry.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[
                [GlobalContextEntrySpecModel1.Builder],
                GlobalContextEntrySpecModel1.Builder | GlobalContextEntrySpecModel1,
            ],
            /,
        ) -> "GlobalContextEntry.Builder": ...

        @overload
        def spec(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntrySpecModel1.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntrySpecModel1.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntrySpecModel1.builder())
                if isinstance(output, GlobalContextEntrySpecModel1.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(
            self, value_or_callback: GlobalContextEntryStatus | None, /
        ) -> "GlobalContextEntry.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[
                [GlobalContextEntryStatus.Builder],
                GlobalContextEntryStatus.Builder | GlobalContextEntryStatus,
            ],
            /,
        ) -> "GlobalContextEntry.Builder": ...

        @overload
        def status(
            self, value_or_callback: Never = ...
        ) -> "GlobalContextEntryStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = GlobalContextEntryStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(GlobalContextEntryStatus.builder())
                if isinstance(output, GlobalContextEntryStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["GlobalContextEntry.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = GlobalContextEntry.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for GlobalContextEntry."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["GlobalContextEntry", Builder]:
        return GenericListBuilder[GlobalContextEntry, GlobalContextEntry.Builder]()

    api_version: Annotated[Literal["kyverno.io/v2alpha1"], Field(alias="apiVersion")] = (
        "kyverno.io/v2alpha1"
    )
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["GlobalContextEntry"] = "GlobalContextEntry"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: GlobalContextEntrySpecModel1
    status: GlobalContextEntryStatus | None = None
